import{$,$$,escapeHtml,formatTime,normalize,toast}from'./utils.js';
import{loadRailData,normalizeLine,hydrateRailLine}from'./data-loader.js';
import{storage}from'./storage.js';
import{Game}from'./game.js';
import{RouteEditor}from'./route-editor.js';
import{renderStats}from'./statistics.js';
import{lineBadgeMarkup}from'./line-badge.js';
import{initAuth}from'./auth.js';

let builtin=[],routes=[],stations=[],selected=null,selectedGroup=null,lastOptions=null,lastRunRoute=null,category='all',operatorFilter='all',featureIndex=0,featureTimer=null,dataLoading=true,pendingRouteId=null,routeRenderLimit=96;
function go(name){const result=window.TRTNavigation?.showScreen(name);requestAnimationFrame(()=>window.scrollTo({top:0,left:0,behavior:'instant'}));return result}
function applyTheme(theme){const resolved=theme==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):theme;document.documentElement.dataset.theme=resolved;document.querySelector('meta[name="theme-color"]')?.setAttribute('content',resolved==='dark'?'#07110e':'#f5f4ef')}
function allRoutes(){return[...builtin,...storage.routes().map(r=>normalizeLine(r,{category:'custom'}))].filter(r=>r.lazy||(Array.isArray(r.stations)&&r.stations.length>=2))}
function operatorLogo(route,className='operator-logo'){const asset=route?.operatorAsset;if(!asset?.asset)return'';return`<span class="${className}"><img loading="lazy" decoding="async" src="${escapeHtml(asset.asset)}" alt="${escapeHtml(asset.label)} 로고"><span hidden>${escapeHtml(asset.label)}</span></span>`}
function operatorKey(route){return route?.operatorAsset?.asset||route?.operatorId||route?.operator?.en}
function renderOperatorFilters(){const unique=[...new Map(routes.map(route=>[operatorKey(route),route])).values()].sort((a,b)=>(a.operator.ko||'').localeCompare(b.operator.ko||'','ko'));$('#operator-filters').innerHTML=`<button class="${operatorFilter==='all'?'active':''}" data-operator="all">전체 운영사</button>`+unique.map(route=>`<button class="${operatorFilter===operatorKey(route)?'active':''}" data-operator="${escapeHtml(operatorKey(route))}">${operatorLogo(route,'filter-logo')}<span>${escapeHtml(route.operator.ko||'MISSING_KOREAN_NAME')}</span></button>`).join('')}
function refreshRoutes(){routes=allRoutes();editor?.setRailNetwork?.(builtin);renderOperatorFilters();renderRoutes()}
function searchable(r){return normalize([r.operator.ja,r.operator.en,r.operator.ko,r.line.ja,r.line.en,r.line.ko,...(r.line.aliases||[]),...(r.searchStations||[]),...(r.stations||[]).flatMap(s=>[s.ja,s.kana,s.romaji,s.ko,...(s.koAliases||[])])].join(' '))}
function searchVariants(value){const base=normalize(value),variants=new Set([base]);for(const [from,to]of [['신칸센','신칸선'],['신칸선','신칸센'],['구마가와','쿠마가와'],['쿠마가와 철도','쿠마가와테츠도우']])if(base.includes(from))variants.add(base.replaceAll(from,to));return[...variants]}
function routeGroup(route){if(route.category==='custom')return'custom';if(route.dataKind==='trainService')return'limited-express';if(route.category==='shinkansen')return'shinkansen';return route.category}
const NETWORK_GROUPS={keio:{nameJa:'京王線系統',nameKo:'게이오선 계통',routeIds:['line-24001','line-24007','line-24004','line-24005','line-24003','line-24002']}};
function filteredRoutes(){const queries=searchVariants($('#route-search').value);return routes.filter(r=>(category==='all'||routeGroup(r)===category)&&(operatorFilter==='all'||operatorKey(r)===operatorFilter)&&(!queries[0]||queries.some(query=>searchable(r).includes(query))))}
function routeCard(r){const ready=r.geometryReady!==false;return`<button class="line-card ${selected?.id===r.id?'selected':''} ${r.category==='shinkansen'?'shinkansen-card':''}" style="--route-color:${r.lineColor}" data-route="${r.id}">${operatorLogo(r,'line-card-operator-logo')}${lineBadgeMarkup(r)}<span class="operator">${escapeHtml(r.operator.ko)} · ${escapeHtml(r.operator.ja)}</span><h3>${escapeHtml(r.line.ko)}</h3><p>${escapeHtml(r.line.ja)}</p><footer><span>${r.stationCount||r.stations.length}개 역</span><span>${ready?(r.lazy?'불러오기':'선택'):'선형 보완 중'} →</span></footer></button>`}
function renderRoutes(){const filtered=filteredRoutes(),query=$('#route-search').value,keio=filtered.filter(r=>NETWORK_GROUPS.keio.routeIds.includes(r.id)),grouped=!query&&keio.length>1,allVisible=grouped?filtered.filter(r=>!NETWORK_GROUPS.keio.routeIds.includes(r.id)):filtered,visible=allVisible.slice(0,routeRenderLimit);$('#route-count').textContent=`${filtered.length}개 노선 · ${Math.min(visible.length,allVisible.length)}개 표시`;const random=category==='all'&&operatorFilter==='all'&&!query?`<button class="line-card random" style="--route-color:#45c985" data-random-route><span class="operator">JAPAN RAIL NETWORK</span><h3>RANDOM</h3><p>전국 랜덤 노선</p><footer><span>PLAYABLE LINES</span><span>SELECT →</span></footer></button>`:'';const group=grouped?`<button class="line-card network-group" style="--route-color:#d4146d" data-route-group="keio">${lineBadgeMarkup(keio[0])}<span class="operator">京王電鉄 · 게이오 전철</span><h3>京王線系統</h3><p>게이오선 계통</p><footer><span>${keio.length} LINES</span><span>BRANCHES →</span></footer></button>`:'';const more=allVisible.length>visible.length?`<button class="line-card route-more" data-route-more><span class="operator">WINDOWED GRID</span><h3>＋ ${Math.min(96,allVisible.length-visible.length)}개 더 보기</h3><p>${allVisible.length-visible.length}개 노선 남음</p></button>`:'';$('#route-grid').innerHTML=random+group+(visible.length?visible.map(routeCard).join('')+more:'<p class="muted">검색 결과가 없습니다.</p>')}
function renderSelected(){const panel=$('#selected-line-preview');if(selectedGroup){const spec=NETWORK_GROUPS[selectedGroup],members=spec.routeIds.map(id=>routes.find(route=>route.id===id)).filter(Boolean);panel.innerHTML=`<div class="selected-line-card network-detail"><p class="eyebrow">MAIN / BRANCHES</p><h3 id="selected-line-heading">${spec.nameJa}<span>${spec.nameKo}</span></h3><div class="network-branches">${members.map(route=>`<button data-route="${route.id}">${lineBadgeMarkup(route)}<span><b>${escapeHtml(route.line.ja)}</b><small>${escapeHtml(route.line.ko)} · ${route.stations.length} STATIONS</small></span></button>`).join('')}</div></div>`;return}if(!selected){panel.innerHTML='<div class="selected-line-empty"><h3 id="selected-line-heading">노선을 선택하세요.</h3><p>오른쪽 목록에서 플레이할 노선을 선택합니다.</p></div>';return}panel.closest('.selected-line-panel').style.setProperty('--route-color',selected.lineColor);panel.innerHTML=`<div class="selected-line-card" style="--route-color:${selected.lineColor}"><div class="selected-line-operator">${operatorLogo(selected,'selected-operator-logo')}${lineBadgeMarkup(selected)}<span>${escapeHtml(selected.operator.ko)}</span></div><h3 id="selected-line-heading">${escapeHtml(selected.line.ja)}<span>${escapeHtml(selected.line.ko)} · ${escapeHtml(selected.line.en)}</span></h3>${selected.section?`<p class="selected-section">${escapeHtml(selected.section.ja)} · ${escapeHtml(selected.section.ko)}</p>`:''}<div class="selected-line-meta"><span>${selected.stations.length} STATIONS</span><span>${selected.dataKind==='trainService'?'LIMITED EXPRESS':selected.loop?'LOOP LINE':'FULL ROUTE'}</span></div><button class="selected-play" type="button" data-selected-play>PLAY THIS LINE <span>→</span></button></div>`}
function throughSpec(route){return(globalThis.TRT_RAIL_SYSTEM?.throughServices||[]).find(item=>item.routeIds.includes(route.id))}
function buildThroughRoute(spec){const parts=[];for(const routeId of spec.routeIds){const part=builtin.find(route=>route.id===routeId);if(!part){console.error('Missing through-service route:',routeId);return null}parts.push(part)}const stations=[],geometry=[],segments=[],stableId=station=>String(station.stationMasterId||station.sourceStationId||station.id);for(const part of parts){let offset=geometry.length;if(geometry.length&&part.geometry?.length&&Math.hypot(geometry.at(-1)[0]-part.geometry[0][0],geometry.at(-1)[1]-part.geometry[0][1])<.002){offset--;geometry.push(...part.geometry.slice(1))}else geometry.push(...part.geometry);const segment={id:part.id,line:part.line,operator:part.operator,operatorAsset:part.operatorAsset,code:part.code,lineColor:part.lineColor,lineTheme:part.lineTheme};const start=stations.length;for(let index=0;index<part.stations.length;index++){const station=part.stations[index],sameBoundary=index===0&&stations.length&&stableId(stations.at(-1))===stableId(station);if(sameBoundary)continue;stations.push({...station,geometryIndex:(station.geometryIndex??0)+offset,segment})}segments.push({...segment,fromStation:start,toStation:stations.length-1})}return{...parts[0],id:`through-${spec.id}`,dataKind:'throughService',line:{ja:spec.nameJa,ko:spec.nameKo,en:spec.nameEn},stations,geometry,segments,services:[{id:'local',nameJa:'各駅停車',nameKo:'각역정차',nameEn:'Local',stops:stations.map(station=>station.id)}],throughService:spec,loop:false,coverage:'verified-through-service'}}
function openSetup(route){selected=route;if(!selected||!Array.isArray(selected.stations)||selected.stations.length<2){toast('플레이 가능한 역이 부족한 노선입니다.');return}const s=storage.settings();$('#game-map-mode').value=s.mapMode;document.querySelector(`#setup-form [name="stationAdvance"][value="${s.stationAdvance}"]`).checked=true;$('#setup-route').style.setProperty('--ticket-color',selected.lineColor);$('#setup-route').innerHTML=`<div class="setup-route-marks">${operatorLogo(selected,'setup-operator-logo')}${lineBadgeMarkup(selected,'setup-line-symbol')}</div><h3>${escapeHtml(selected.line.ja)}</h3><p>${escapeHtml(selected.operator.en)} · ${escapeHtml(selected.line.en)}<br>${escapeHtml(selected.line.ko)} · ${selected.stations.length} STATIONS</p>${selected.section?`<p class="setup-section">${escapeHtml(selected.section.ja)} · ${escapeHtml(selected.section.ko)}</p>`:''}<ol class="setup-stations">${selected.stations.map(station=>`<li><b>${escapeHtml(station.ja)}</b><span>${escapeHtml(station.romaji)} · ${escapeHtml(station.ko)}</span></li>`).join('')}</ol><div class="route-endpoints"><span>${escapeHtml(selected.stations[0].ja)}<small> 출발</small></span><span>${escapeHtml(selected.stations.at(-1).ja)}<small> 종착</small></span></div>`;const services=selected.services?.length?selected.services:[{id:'local',nameJa:'各駅停車',nameKo:'각역정차',stops:selected.stations.map(station=>station.id)}];$('#service-options').style.setProperty('--route-color',selected.lineColor);$('#service-options').innerHTML=services.map((service,index)=>`<label><input type="radio" name="service" value="${escapeHtml(service.id)}" ${index?'':'checked'}><span><b>${escapeHtml(service.nameJa)} · ${escapeHtml(service.nameKo)}</b><small>${service.stops.length} STOPS</small></span></label>`).join('');const first=selected.stations[0],last=selected.stations.at(-1),direction=$('#service-direction');direction.innerHTML=selected.loop?`<option value="forward">내선 순환 · ${escapeHtml(first.ja)} 출발</option><option value="reverse">외선 순환 · ${escapeHtml(first.ja)} 출발</option>`:`<option value="forward">${escapeHtml(first.ja)} → ${escapeHtml(last.ja)}</option><option value="reverse">${escapeHtml(last.ja)} → ${escapeHtml(first.ja)}</option>`;const direct=throughSpec(selected),field=$('#through-service-fieldset'),destination=$('#through-destination');field.hidden=!direct;if(direct){destination.innerHTML=direct.allowedDestinations.map(name=>`<option value="${escapeHtml(name)}">${escapeHtml(name)}</option>`).join('');field.querySelector('[name="directService"][value="off"]').checked=true}go('game-setup')}
async function chooseRoute(id){let route=routes.find(r=>r.id===id);if(!route&&dataLoading){pendingRouteId=id;toast('철도 데이터를 불러오는 중입니다. 잠시만 기다려 주세요.');return false}if(!route){console.warn('Line not found:',id);toast('선택한 노선을 찾을 수 없습니다. 데이터를 다시 불러와 주세요.');return false}if(route.lazy){toast(`${route.line.ko} 실제 역·선형을 불러오는 중입니다.`);try{const hydrated=await hydrateRailLine(route),index=builtin.findIndex(item=>item.id===id);if(index>=0)builtin[index]=hydrated;refreshRoutes();route=routes.find(item=>item.id===id)}catch(error){console.error('Nationwide line load failed:',error);toast('이 노선의 상세 데이터를 불러오지 못했습니다.');return false}}selected=route;if(currentScreen!=='rail-map')go('rail-map');renderSelected();renderRoutes();return true}
function renderHome(){const recent=storage.recent();$$('[data-feature-route]').forEach(button=>{const route=routes.find(item=>item.id===button.dataset.featureRoute),slot=button.closest('article')?.querySelector('.feature-number');if(route&&slot){slot.innerHTML=lineBadgeMarkup(route);slot.hidden=!slot.innerHTML}});$('#recent-list').innerHTML=recent.length?recent.slice(0,3).map(record=>{const route=routes.find(item=>item.id===record.routeId);return`<button class="recent-chip" data-feature-route="${escapeHtml(record.routeId)}" style="--route-color:${record.color}">${route?lineBadgeMarkup(route):''}<span><b>${escapeHtml(record.routeName)}</b><small>${formatTime(record.elapsed)} · ${record.accuracy.toFixed(1)}%</small></span></button>`}).join(''):'<p class="muted">아직 운행 기록이 없습니다.</p>'}
function renderCustomLibrary(){const list=storage.routes(),target=$('#custom-route-library');target.innerHTML=list.length?list.map(r=>`<article class="library-card" style="--route-color:${r.lineColor}" data-library-route="${r.id}"><span class="library-code">${escapeHtml(r.code||'CT')} · ${r.stations.length} STATIONS</span><h3>${escapeHtml(r.line.ko)}</h3><p>${escapeHtml(r.line.ja)} · ${escapeHtml(r.line.en)}</p><footer><button class="btn primary" data-library-play>PLAY</button><button class="btn ghost" data-library-edit>EDIT</button><button class="btn text" data-library-delete aria-label="${escapeHtml(r.line.ko)} 삭제">×</button></footer></article>`).join(''):`<div class="library-empty"><b>아직 만든 노선이 없습니다.</b><p>첫 노선을 만들고 원하는 역 순서로 달려보세요.</p><button class="btn primary" data-action="custom-new">＋ CREATE NEW ROUTE</button></div>`}
function showResult(result){const isRecord=storage.saveResult(result);$('#result-operator-logo').innerHTML=result.route.operatorAsset?`<img src="${escapeHtml(result.route.operatorAsset.asset)}" alt="${escapeHtml(result.route.operatorAsset.label)} 로고">`:'';$('#result-line-badge').innerHTML=lineBadgeMarkup(result.route);$('#result-route').textContent=`${result.route.line.ja} · ${result.route.line.ko} · ${result.route.operator.ko}`;$('#result-time').textContent=formatTime(result.elapsed);$('#result-accuracy').textContent=`${result.accuracy.toFixed(1)}%`;$('#result-cpm').textContent=`${result.cpm} 타/min`;$('#result-errors').textContent=result.errors;$('#result-combo').textContent=result.maxCombo;$('#result-wpm').textContent=result.wpm;$('#record-notice').hidden=!isRecord;go('result')}
const game=new Game({onFinish:showResult,onQuit:()=>go('select')});
const editor=new RouteEditor({onRoutesChanged:()=>{refreshRoutes();renderCustomLibrary()},onPlay:openSetup,onSaved:()=>go('custom-list')});
let currentScreen=document.body.dataset.currentScreen||'home';
window.addEventListener('trt:screenchange',e=>{const name=e.detail.name;if(currentScreen==='game'&&name!=='game')game?.stop(false);currentScreen=name;if(name==='rail-map')renderRoutes();if(name==='records')renderStats();if(name==='home')renderHome();if(name==='custom-list')renderCustomLibrary();if(name==='custom-editor')editor.activate()});
$('#category-tabs').addEventListener('click',e=>{if(!e.target.dataset.category)return;category=e.target.dataset.category;routeRenderLimit=96;$$('button',$('#category-tabs')).forEach(b=>b.classList.toggle('active',b===e.target));renderRoutes()});
$('#operator-filters').addEventListener('click',e=>{const button=e.target.closest('[data-operator]');if(!button)return;operatorFilter=button.dataset.operator;routeRenderLimit=96;$$('button',$('#operator-filters')).forEach(item=>item.classList.toggle('active',item===button));renderRoutes()});
$('#route-search').addEventListener('input',()=>{routeRenderLimit=96;renderRoutes()});
$('#route-grid').addEventListener('click',e=>{if(e.target.closest('[data-route-more]')){routeRenderLimit+=96;renderRoutes();return}const group=e.target.closest('[data-route-group]');if(group){selected=null;selectedGroup=group.dataset.routeGroup;renderSelected();renderRoutes();return}const random=e.target.closest('[data-random-route]');if(random){const playable=filteredRoutes();if(playable.length)chooseRoute(playable[Math.floor(Math.random()*playable.length)].id);return}const card=e.target.closest('[data-route]');if(card){selectedGroup=null;chooseRoute(card.dataset.route)}});
$('#selected-line-preview').addEventListener('click',e=>{const branch=e.target.closest('[data-route]');if(branch){selectedGroup=null;chooseRoute(branch.dataset.route);return}if(e.target.closest('[data-selected-play]')&&selected)openSetup(selected)});
$('#clear-route-selection').addEventListener('click',()=>{selected=null;selectedGroup=null;renderSelected();renderRoutes()});
document.addEventListener('click',e=>{const create=e.target.closest('[data-action="custom-new"]');if(create){editor.createNew();go('custom-editor');return}const featured=e.target.closest('[data-feature-route]');if(featured){chooseRoute(featured.dataset.featureRoute);return}const card=e.target.closest('[data-library-route]');if(!card)return;const route=storage.routes().find(r=>r.id===card.dataset.libraryRoute);if(!route)return;if(e.target.closest('[data-library-play]'))openSetup(route);else if(e.target.closest('[data-library-edit]')){editor.loadRoute(route);go('custom-editor')}else if(e.target.closest('[data-library-delete]')&&confirm('이 노선을 삭제할까요?')){storage.deleteRoute(route.id);refreshRoutes();renderCustomLibrary();toast('노선을 삭제했습니다.')}});
$('#setup-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target),settings=storage.settings(),stationLabel=['ja','ja-romaji'].includes(settings.stationLabel)?settings.stationLabel:'ja',direct=throughSpec(selected);lastRunRoute=data.get('directService')==='on'&&direct?buildThroughRoute(direct):selected;if(!lastRunRoute)return toast('직결운행 데이터를 준비하지 못했습니다.');lastOptions={mode:data.get('mode'),inputMode:data.get('inputMode')||'shadowing',difficulty:data.get('difficulty'),service:data.get('service'),direction:$('#service-direction').value,display:'ja',input:'ko',stationAdvance:data.get('stationAdvance')||settings.stationAdvance,mapMode:$('#game-map-mode').value,stationLabel,mapLabels:settings.mapLabels,motion:settings.motion,reducedMotion:settings.reducedMotion,sound:settings.sound};if(lastRunRoute.dataKind==='throughService'){lastOptions.service='local';lastOptions.direction='forward'}$('#map-view-toggle').textContent=lastOptions.mapMode==='geographic'?'SCHEMATIC':'GEOGRAPHIC';if(game.start(lastRunRoute,lastOptions)){go('game');game.focusInput()}});
$('#retry-game').addEventListener('click',()=>{if(game.start(lastRunRoute||selected,lastOptions)){go('game');game.focusInput()}});
$('#map-view-toggle').addEventListener('click',()=>game.toggleMapMode());
$('#settings-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),settings={...storage.settings(),theme:f.get('theme'),stationAdvance:f.get('stationAdvance'),display:'ja',input:'ko',mapMode:f.get('mapMode'),stationLabel:f.get('stationLabel'),mapLabels:f.get('mapLabels'),sound:f.get('sound')==='on',motion:f.get('motion')==='on',reducedMotion:f.get('reducedMotion')==='on'};storage.saveSettings(settings);applyTheme(settings.theme);document.body.classList.toggle('reduce-motion',settings.reducedMotion);toast('설정을 저장했습니다.')});
const settings=storage.settings(),sf=$('#settings-form').elements;sf.theme.value=settings.theme;sf.stationAdvance.value=settings.stationAdvance;sf.mapMode.value=settings.mapMode;sf.stationLabel.value=['ja','ja-romaji'].includes(settings.stationLabel)?settings.stationLabel:'ja';sf.mapLabels.value=settings.mapLabels;sf.sound.checked=settings.sound;sf.motion.checked=settings.motion;sf.reducedMotion.checked=settings.reducedMotion;applyTheme(settings.theme);document.body.classList.toggle('reduce-motion',settings.reducedMotion);matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if(storage.settings().theme==='system')applyTheme('system')});
$('#game-theme-toggle').addEventListener('click',()=>{const current=document.documentElement.dataset.theme,next=current==='dark'?'light':'dark',updated={...storage.settings(),theme:next};storage.saveSettings(updated);sf.theme.value=next;applyTheme(next);game.refreshMap()});
const updateClock=()=>$('#clock').textContent=new Intl.DateTimeFormat('ko-KR',{hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date());updateClock();setInterval(updateClock,1000);
function setFeature(next){featureIndex=(next+3)%3;$$('[data-feature-index]').forEach((card,i)=>card.classList.toggle('active',i===featureIndex));$$('[data-slide-to]').forEach((dot,i)=>dot.classList.toggle('active',i===featureIndex));$('#feature-counter').textContent=`0${featureIndex+1} / 03`}
function restartFeatureTimer(){clearInterval(featureTimer);if(matchMedia('(prefers-reduced-motion: reduce)').matches||document.body.classList.contains('reduce-motion'))return;featureTimer=setInterval(()=>setFeature(featureIndex+1),7000)}
document.querySelector('.feature-controls').addEventListener('click',e=>{const direction=e.target.closest('[data-slide]')?.dataset.slide,to=e.target.closest('[data-slide-to]')?.dataset.slideTo;if(direction)setFeature(featureIndex+(direction==='next'?1:-1));if(to!==undefined)setFeature(+to);restartFeatureTimer()});
$('#feature-viewport').addEventListener('mouseenter',()=>clearInterval(featureTimer));$('#feature-viewport').addEventListener('mouseleave',restartFeatureTimer);restartFeatureTimer();
$('#library-import').addEventListener('change',async e=>{await editor.import(e.target.files[0]);e.target.value='';renderCustomLibrary();go('custom-editor')});
initAuth(storage);renderHome();renderCustomLibrary();refreshRoutes();if(currentScreen==='records')renderStats();if(['game','game-setup','result'].includes(currentScreen)){window.TRTNavigation?.showScreen('rail-map',{history:'replace'});toast('노선을 먼저 선택해 주세요.')}
async function reloadRailData(){const summary=$('#data-summary');dataLoading=true;summary.classList.remove('error');summary.textContent='전국 철도 카탈로그를 불러오는 중...';try{const loaded=await loadRailData();builtin=loaded.lines;stations=loaded.stations;editor.setStationMaster(stations);refreshRoutes();renderHome();summary.innerHTML=`전국 ${builtin.length}개 · JR ${loaded.counts.jr||0} · 지하철 ${loaded.counts.subway||0} · 사철 ${loaded.counts.private||0} · 제3섹터 ${loaded.counts['third-sector']||0} · 트램 ${loaded.counts.tram||0} · 신칸센 ${loaded.counts.shinkansen||0}`;dataLoading=false;if(pendingRouteId){const id=pendingRouteId;pendingRouteId=null;chooseRoute(id)}if(loaded.errors.length&&!builtin.some(route=>route.lazy)){summary.classList.add('error');summary.innerHTML=`일부 철도 데이터를 불러오지 못했습니다. 사용 가능한 ${builtin.length}개 노선으로 계속할 수 있습니다. <button data-retry-data>다시 시도</button>`}return loaded}catch(error){console.error('App rail data initialization failed:',error);builtin=[];editor.setStationMaster([]);refreshRoutes();renderHome();dataLoading=false;summary.classList.add('error');summary.innerHTML='철도 데이터를 불러오지 못했습니다. <button data-retry-data>다시 시도</button>';return null}}
document.addEventListener('click',e=>{if(e.target.closest('[data-retry-data]'))reloadRailData()});
function runSanityChecks(){console.assert(routes.length>0,'Rail data must contain playable lines');console.assert(routes.some(line=>line.id==='line-11302'),'Yamanote line is required');console.assert(routes.some(line=>line.id==='line-28001'),'Ginza line is required');console.assert(routes.every(line=>line.lazy||(Array.isArray(line.stations)&&line.stations.length>=2)),'Every visible line must be playable or lazy-loadable')}
await reloadRailData();if(['localhost','127.0.0.1'].includes(location.hostname))runSanityChecks();
