import{$,$$,escapeHtml,formatTime,normalize,toast}from'./utils.js';
import{loadTransportData,normalizeLine,hydrateRailLine}from'./data-loader.js';
import{storage}from'./storage.js';
import{Game}from'./game.js';
import{RouteEditor}from'./route-editor.js';
import{renderStats}from'./statistics.js';
import{lineBadgeMarkup}from'./line-badge.js';
import{operatorLogoMarkup}from'./asset-renderer.js';
import{initAuth}from'./auth.js';
import{railDataRepository}from'./rail-data-repository.js';
import{FEATURE_FLAGS,isCountryEnabled,isRouteVisible}from'./feature-flags.js';
import{buildThroughServiceRoute,resolveServiceJourney,resolveServiceSelection,serviceJourneysForRoute,servicePatternsForRoute,trainTypeFor}from'./service-route-resolver.js';

const savedCountryId=localStorage.getItem('trt-country')||'jp';
let builtin=[],routes=[],stations=[],selected=null,selectedGroup=null,lastOptions=null,lastRunRoute=null,transportGroup='all',category='all',regionFilter='all',operatorFilter='all',featureIndex=0,featureTimer=null,dataLoading=true,pendingRouteId=null,routeRenderLimit=96,countryId=isCountryEnabled(savedCountryId)?savedCountryId:'jp';
const KR_REGIONS=[['all','전국'],['seoul','서울'],['busan','부산'],['daegu','대구'],['incheon','인천'],['gwangju','광주'],['daejeon','대전'],['ulsan','울산'],['sejong','세종'],['gyeonggi','경기'],['gangwon','강원'],['chungbuk','충북'],['chungnam','충남'],['jeonbuk','전북'],['jeonnam','전남'],['gyeongbuk','경북'],['gyeongnam','경남'],['jeju','제주']];
const KR_GROUPS=[['all','전체'],['rail','철도'],['bus','버스'],['water','수상교통'],['other','기타 교통'],['custom','커스텀']];
const KR_CATEGORIES={rail:[['all','전체 철도'],['subway','지하철·도시철도'],['commuter_rail','광역철도'],['rail','일반철도'],['high_speed_rail','고속철도'],['light_rail','경전철'],['monorail','모노레일'],['tram','노면전차'],['airport_rail','공항철도'],['other_rail','기타 철도']],water:[['all','전체 수상교통'],['river_bus','한강버스'],['ferry','여객선']],other:[['all','전체 기타 교통']]};
const JP_CATEGORIES=[['all','전체'],['jr','JR'],['subway','지하철'],['private','사철'],['third-sector','제3섹터'],['tram','노면전차'],['other','기타'],['shinkansen','신칸센'],['limited-express','특급'],['custom','커스텀']];
const COUNTRY_UI={jp:{mark:'JAPAN RAIL',status:'日本全国 · ALL JAPAN',subtitle:'일본 전국 철도 타이핑',title:'일본 철도를<br><span>타이핑하다.</span>',intro:'일본 전국의 실제 역 순서와 선형을 따라 달리는 철도 타이핑 게임.<br>현재역에서 다음역으로, 한국어 역명을 정확히 입력하세요.',network:'JAPAN RAILWAY NETWORK / 日本全国'},kr:{mark:'KOREA TRANSIT',status:'대한민국 · KOREA',subtitle:'대한민국 대중교통 타이핑',title:'대한민국 교통을<br><span>타이핑하다.</span>',intro:'철도·지하철·버스·수상교통의 실제 정차 순서를 따라가는 타이핑 게임.<br>한국어 역·정류장·선착장 이름을 정확히 입력하세요.',network:'KOREA PUBLIC TRANSPORT / 대한민국'}};
const renderTabs=(target,items,dataKey,current)=>{target.innerHTML=items.map(([id,label])=>`<button class="${id===current?'active':''}" data-${dataKey}="${id}">${label}</button>`).join('')};
function busCategories(){const scoped=routes.filter(route=>routeTransportGroup(route)==='bus'&&(regionFilter==='all'||route.regionId===regionFilter)),values=new Map([['all','전체']]);for(const route of scoped)values.set(route.normalizedCategory||route.routeType||route.category,route.regionalCategory||route.routeType||route.category);return[...values]}
function renderTransportFilters(){const groupTabs=$('#transport-mode-tabs'),regionTabs=$('#region-tabs'),categoryTabs=$('#category-tabs');if(countryId==='jp'){groupTabs.hidden=true;regionTabs.hidden=true;categoryTabs.hidden=false;renderTabs(categoryTabs,JP_CATEGORIES.filter(([id])=>id==='all'||id==='custom'||routes.some(route=>routeGroup(route)===id)),'category',category);return}groupTabs.hidden=false;renderTabs(groupTabs,KR_GROUPS,'transport-group',transportGroup);regionTabs.hidden=transportGroup!=='bus';if(transportGroup==='bus')renderTabs(regionTabs,KR_REGIONS,'region',regionFilter);const items=transportGroup==='bus'?busCategories():KR_CATEGORIES[transportGroup]||[];categoryTabs.hidden=!items.length;if(items.length)renderTabs(categoryTabs,items,'category',category)}
function applyCountryUi(){const ui=COUNTRY_UI[countryId];document.documentElement.dataset.country=countryId;document.documentElement.dataset.featureKorea=String(FEATURE_FLAGS.korea);$('#brand-subtitle').textContent=ui.subtitle;$('#home-country-mark').textContent=ui.mark;$('#home-country-subtitle').textContent=ui.subtitle;$('#home-country-status').textContent=ui.status;$('#hero-title').innerHTML=ui.title;$('#home-intro').innerHTML=ui.intro;document.querySelector('.line-select-heading p').textContent=ui.network;renderTransportFilters();$$('[data-country]').forEach(button=>{const enabled=isCountryEnabled(button.dataset.country);button.hidden=!enabled;button.disabled=!enabled;button.setAttribute('aria-hidden',String(!enabled));button.classList.toggle('active',enabled&&button.dataset.country===countryId)})}
function refreshCountryCopy(){const korea=countryId==='kr',play=document.querySelector('.launch-menu [data-nav="rail-map"] small'),footer=document.querySelector('.home-footer span:nth-child(2)'),featureButtons=$$('#feature-viewport [data-feature-route]');if(play)play.textContent=korea?'대한민국 교통에서 노선 선택':'일본 전국 철도에서 노선 선택';if(footer)footer.textContent=korea?'대한민국 대중교통 타이핑':'일본 전국 철도 타이핑';if(featureButtons[0])featureButtons[0].dataset.featureRoute=korea?'kr-seoul-line-2':'line-11302';if(featureButtons[1])featureButtons[1].dataset.featureRoute=korea?'kr-shinbundang':'line-28001'}
function configureExplicitDirections(){if(!selected?.directions?.length)return;const select=$('#service-direction'),name=stop=>stop?.ko||stop?.names?.ko||'';select.innerHTML=selected.directions.map(direction=>`<option value="${escapeHtml(direction.id)}">${escapeHtml(direction.names?.ko||direction.id)} · ${escapeHtml(name(direction.stops?.[0]))} → ${escapeHtml(name(direction.stops?.at(-1)))}</option>`).join('')}
function applyExplicitDirection(){const select=$('#service-direction'),direction=selected?.directions?.find(item=>item.id===select.value);if(!direction)return;selected=railDataRepository.resolveRoute(normalizeLine({...selected,lazy:false,selectedDirectionId:direction.id,selectedDirectionName:direction.names?.ko||direction.id,stations:direction.stops,directions:selected.directions,geometry:direction.geometry||[],directedSegments:direction.directedSegments||[],geometryReady:direction.geometryStatus==='ready',services:[]},{category:selected.category}));select.innerHTML=`<option value="forward">${escapeHtml(direction.names?.ko||direction.id)}</option>`}
function go(name){const result=window.TRTNavigation?.showScreen(name);requestAnimationFrame(()=>window.scrollTo({top:0,left:0,behavior:'instant'}));return result}
function applyTheme(theme){const resolved=theme==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):theme;document.documentElement.dataset.theme=resolved;document.querySelector('meta[name="theme-color"]')?.setAttribute('content',resolved==='dark'?'#07110e':'#f5f4ef')}
function allRoutes(){return[...builtin,...storage.routes().filter(route=>isCountryEnabled(route.countryId||'jp')).map(r=>railDataRepository.resolveRoute(normalizeLine(r,{category:'custom'})))].filter(isRouteVisible).filter(r=>r.lazy||(Array.isArray(r.stations)&&r.stations.length>=2))}
const operatorLogo=operatorLogoMarkup;
function operatorKey(route){return route?.operatorId||route?.operator?.en}
function renderOperatorFilters(){const context=routes.filter(route=>countryId==='jp'||transportGroup==='all'||routeTransportGroup(route)===transportGroup).filter(route=>transportGroup!=='bus'||regionFilter==='all'||route.regionId===regionFilter),unique=[...new Map(context.map(route=>[operatorKey(route),route])).values()].sort((a,b)=>(a.operator.ko||'').localeCompare(b.operator.ko||'','ko'));$('#operator-filters').innerHTML=`<button class="${operatorFilter==='all'?'active':''}" data-operator="all">전체 운영사</button>`+unique.map(route=>`<button class="${operatorFilter===operatorKey(route)?'active':''}" data-operator="${escapeHtml(operatorKey(route))}">${operatorLogo(route,'filter-logo')}<span>${escapeHtml(route.operator.ko||'MISSING_KOREAN_NAME')}</span></button>`).join('')}
function refreshRoutes(){routes=allRoutes();editor?.setRailNetwork?.(builtin.filter(isRouteVisible));renderTransportFilters();renderOperatorFilters();renderRoutes();refreshFeatureCounts()}
function refreshFeatureCounts(){document.querySelectorAll('#feature-viewport [data-feature-route]').forEach(button=>{const route=routes.find(item=>item.id===button.dataset.featureRoute),target=button.closest('article')?.querySelector('[data-feature-stations]');if(route&&target)target.textContent=`${route.stationCount||route.stations.length}개 ${stopWord(route)}`})}
function searchable(r){return normalize([r.operator.ja,r.operator.en,r.operator.ko,r.line.ja,r.line.en,r.line.ko,...(r.line.aliases||[]),...(r.searchStations||[]),...(r.stations||[]).flatMap(s=>[s.ja,s.kana,s.romaji,s.ko,...(s.koAliases||[])])].join(' '))}
function searchVariants(value){const base=normalize(value),variants=new Set([base]);for(const [from,to]of [['구마가와','쿠마가와'],['쿠마가와 철도','쿠마가와테츠도우']])if(base.includes(from))variants.add(base.replaceAll(from,to));return[...variants]}
function routeGroup(route){if(route.category==='custom')return'custom';if(countryId==='jp'&&route.dataKind==='trainService')return'limited-express';if(route.category==='shinkansen')return'shinkansen';return route.category}
function routeTransportGroup(route){if(route.category==='custom')return'custom';if(['bus','village_bus','express_bus','brt'].includes(route.mode))return'bus';if(['river_bus','ferry'].includes(route.mode))return'water';if(['rail','subway','commuter_rail','high_speed_rail','light_rail','monorail','tram','airport_rail'].includes(route.mode))return'rail';return'other'}
function routeCategoryMatches(route){if(category==='all')return true;if(transportGroup==='bus')return(category===(route.normalizedCategory||route.routeType||route.category));return routeGroup(route)===category||route.mode===category}
const NETWORK_GROUPS={keio:{routeIds:['line-24001','line-24007','line-24004','line-24005','line-24003','line-24002']}};
function filteredRoutes(){const queries=searchVariants($('#route-search').value);return routes.filter(r=>(countryId==='jp'||transportGroup==='all'||routeTransportGroup(r)===transportGroup)&&(countryId!=='kr'||transportGroup!=='bus'||regionFilter==='all'||r.regionId===regionFilter)&&routeCategoryMatches(r)&&(operatorFilter==='all'||operatorKey(r)===operatorFilter)&&(!queries[0]||queries.some(query=>searchable(r).includes(query))))}
function stopWord(route){return['bus','village_bus','express_bus','brt'].includes(route.mode)?'정류장':['river_bus','ferry'].includes(route.mode)?'선착장':'역'}
function routeCard(r){const ready=r.geometryReady!==false,word=stopWord(r);return`<button class="line-card ${selected?.id===r.id?'selected':''} ${r.category==='shinkansen'?'shinkansen-card':''}" style="--route-color:${r.lineColor}" data-route="${r.id}">${operatorLogo(r,'line-card-operator-logo')}${lineBadgeMarkup(r)}<span class="operator">${escapeHtml(r.operator.ko)}${r.operator.ja?` · ${escapeHtml(r.operator.ja)}`:''}</span><h3>${escapeHtml(r.line.ko)}</h3><p>${escapeHtml(r.line.ja||r.line.en)}</p><footer><span>${r.stationCount||r.stations.length}개 ${word}</span><span>${r.lazy?'상세 불러오기':ready?'선택':'순서 플레이'} →</span></footer></button>`}
function renderRoutes(){const filtered=filteredRoutes(),query=$('#route-search').value,keio=countryId==='jp'?filtered.filter(r=>NETWORK_GROUPS.keio.routeIds.includes(r.id)):[],grouped=!query&&keio.length>1,allVisible=grouped?filtered.filter(r=>!NETWORK_GROUPS.keio.routeIds.includes(r.id)):filtered,visible=allVisible.slice(0,routeRenderLimit);$('#route-count').textContent=`${filtered.length}개 노선 · ${Math.min(visible.length,allVisible.length)}개 표시`;const random=category==='all'&&transportGroup==='all'&&operatorFilter==='all'&&!query?`<button class="line-card random" style="--route-color:#45c985" data-random-route><span class="operator">${countryId==='kr'?'KOREA TRANSIT NETWORK':'JAPAN RAIL NETWORK'}</span><h3>RANDOM</h3><p>${countryId==='kr'?'대한민국':'일본 전국'} 랜덤 노선</p><footer><span>PLAYABLE ROUTES</span><span>SELECT →</span></footer></button>`:'';const group=grouped?`<button class="line-card network-group" style="--route-color:#d4146d" data-route-group="keio">${lineBadgeMarkup(keio[0])}<span class="operator">${escapeHtml(keio[0].operator.ja)} · ${escapeHtml(keio[0].operator.ko)}</span><h3>${escapeHtml(keio[0].line.ja)}系統</h3><p>${escapeHtml(keio[0].line.ko)} 계통</p><footer><span>${keio.length} LINES</span><span>BRANCHES →</span></footer></button>`:'';const more=allVisible.length>visible.length?`<button class="line-card route-more" data-route-more><span class="operator">WINDOWED GRID</span><h3>＋ ${Math.min(96,allVisible.length-visible.length)}개 더 보기</h3><p>${allVisible.length-visible.length}개 노선 남음</p></button>`:'';$('#route-grid').innerHTML=random+group+(visible.length?visible.map(routeCard).join('')+more:'<p class="muted">검색 결과가 없습니다.</p>')}
function renderSelected(){const panel=$('#selected-line-preview');if(selectedGroup){const spec=NETWORK_GROUPS[selectedGroup],members=spec.routeIds.map(id=>routes.find(route=>route.id===id)).filter(Boolean),main=members[0];panel.innerHTML=`<div class="selected-line-card network-detail"><p class="eyebrow">MAIN / BRANCHES</p><h3 id="selected-line-heading">${escapeHtml(main?.line.ja||'')}系統<span>${escapeHtml(main?.line.ko||'')} 계통</span></h3><div class="network-branches">${members.map(route=>`<button data-route="${route.id}">${lineBadgeMarkup(route)}<span><b>${escapeHtml(route.line.ja)}</b><small>${escapeHtml(route.line.ko)} · ${route.stations.length} STATIONS</small></span></button>`).join('')}</div></div>`;return}if(!selected){panel.innerHTML='<div class="selected-line-empty"><h3 id="selected-line-heading">노선을 선택하세요.</h3><p>오른쪽 목록에서 플레이할 노선을 선택합니다.</p></div>';return}panel.closest('.selected-line-panel').style.setProperty('--route-color',selected.lineColor);panel.innerHTML=`<div class="selected-line-card" style="--route-color:${selected.lineColor}"><div class="selected-line-operator">${operatorLogo(selected,'selected-operator-logo')}${lineBadgeMarkup(selected)}<span>${escapeHtml(selected.operator.ko)}</span></div><h3 id="selected-line-heading">${escapeHtml(selected.line.ja)}<span>${escapeHtml(selected.line.ko)} · ${escapeHtml(selected.line.en)}</span></h3>${selected.section?`<p class="selected-section">${escapeHtml(selected.section.ja)} · ${escapeHtml(selected.section.ko)}</p>`:''}<div class="selected-line-meta"><span>${selected.stations.length} STATIONS</span><span>${selected.dataKind==='trainService'?'LIMITED EXPRESS':selected.loop?'LOOP LINE':'FULL ROUTE'}</span></div><button class="selected-play" type="button" data-selected-play>PLAY THIS LINE <span>→</span></button></div>`}
function throughRouteIds(spec){return spec.routeSegments?.map(segment=>segment.routeId)||spec.routeIds||[]}
function throughSpec(route){return(globalThis.TRT_RAIL_SYSTEM?.throughServices||[]).find(item=>throughRouteIds(item).includes(route.id))}
function buildThroughRoute(spec){
  try{return buildThroughServiceRoute(spec,id=>builtin.find(route=>route.id===id))}catch(error){console.error(error);return null}
}
const journeyLabel=names=>names?.ko||names?.ja||names?.en||'';
function configureJourneyPicker(){
  const journeys=serviceJourneysForRoute(selected?.id),picker=$('#journey-picker'),options=$('#service-options'),direction=$('#service-direction'),directionLabel=direction.closest('label');picker.hidden=!journeys.length;options.hidden=!!journeys.length;directionLabel.hidden=!!journeys.length;if(!journeys.length)return;
  const origin=$('#journey-origin'),destination=$('#journey-destination'),train=$('#journey-train-type'),summary=$('#journey-summary'),unique=items=>[...new Map(items.map(item=>[item.stationId,item])).values()];
  const renderTrainTypes=()=>{const candidates=journeys.filter(item=>item.originStationId===origin.value&&item.destinationStationId===destination.value),types=[...new Map(candidates.map(item=>[item.trainTypeId,trainTypeFor(item.trainTypeId)])).values()].filter(Boolean);train.innerHTML=types.map(item=>`<option value="${escapeHtml(item.id)}">${escapeHtml(item.names.ko)} · ${escapeHtml(item.names.ja)}</option>`).join('');const chosen=candidates.find(item=>item.trainTypeId===train.value)||candidates[0];summary.textContent=chosen?`${journeyLabel(chosen.originNames)} → ${journeyLabel(chosen.destinationNames)} · ${journeyLabel(trainTypeFor(chosen.trainTypeId)?.names)} · 하나의 연속 운행`:''};
  const renderDestinations=()=>{const destinations=unique(journeys.filter(item=>item.originStationId===origin.value).map(item=>({stationId:item.destinationStationId,names:item.destinationNames})));destination.innerHTML=destinations.map(item=>`<option value="${escapeHtml(item.stationId)}">${escapeHtml(journeyLabel(item.names))}</option>`).join('');renderTrainTypes()};
  const origins=unique(journeys.map(item=>({stationId:item.originStationId,names:item.originNames})));origin.innerHTML=origins.map(item=>`<option value="${escapeHtml(item.stationId)}">${escapeHtml(journeyLabel(item.names))}</option>`).join('');origin.onchange=renderDestinations;destination.onchange=renderTrainTypes;train.onchange=renderTrainTypes;renderDestinations();
}
function openSetup(route){
  selected=route;if(!selected||!Array.isArray(selected.stations)||selected.stations.length<2){toast('플레이 가능한 역이 부족한 노선입니다.');return}
  const settings=storage.settings(),patterns=servicePatternsForRoute(selected.id);$('#game-map-mode').value=settings.mapMode;document.querySelector(`#setup-form [name="stationAdvance"][value="${settings.stationAdvance}"]`).checked=true;
  $('#setup-route').style.setProperty('--ticket-color',selected.lineColor);$('#setup-route').innerHTML=`<div class="setup-route-marks">${operatorLogo(selected,'setup-operator-logo')}${lineBadgeMarkup(selected,'setup-line-symbol')}</div><h3>${escapeHtml(selected.line.ja)}</h3><p>${escapeHtml(selected.operator.en)} · ${escapeHtml(selected.line.en)}<br>${escapeHtml(selected.line.ko)} · ${selected.stations.length} STATIONS</p>${selected.section?`<p class="setup-section">${escapeHtml(selected.section.ja)} · ${escapeHtml(selected.section.ko)}</p>`:''}<ol class="setup-stations">${selected.stations.map(station=>`<li><b>${escapeHtml(station.ja)}</b><span>${escapeHtml(station.romaji)} · ${escapeHtml(station.ko)}</span></li>`).join('')}</ol><div class="route-endpoints"><span>${escapeHtml(selected.stations[0].ja)}<small> 출발</small></span><span>${escapeHtml(selected.stations.at(-1).ja)}<small> 종착</small></span></div>`;
  const services=selected.services?.length?selected.services:[{id:'local',nameJa:'各駅停車',nameKo:'각역정차',stops:selected.stations.map(station=>station.id)}],choices=patterns.length?patterns:services;
  $('#service-fieldset legend').textContent=patterns.length?'운행계통 · 열차종별 · 행선지':'열차 종류';$('#service-options').style.setProperty('--route-color',selected.lineColor);$('#service-options').innerHTML=choices.map((choice,index)=>{const trainType=choice.trainTypeId?trainTypeFor(choice.trainTypeId):null,destination=choice.destinationStationId?(selected.stations.find(station=>station.id===choice.destinationStationId)?.ko||choice.names?.ko?.replace(/^.*?\s(?=\S+행$)/,'')||'직통 행선지'):'';return`<label><input type="radio" name="service" value="${escapeHtml(choice.id)}" ${index?'':'checked'}><span><b>${escapeHtml(choice.names?.ja||choice.nameJa)} · ${escapeHtml(choice.names?.ko||choice.nameKo)}</b><small>${trainType?`${escapeHtml(trainType.names.ko)} · `:''}${destination?`${escapeHtml(destination)} · `:''}${choice.stopStationIds?.length||choice.stops?.length||'ALL'} STOPS</small></span></label>`}).join('');
  const first=selected.stations[0],last=selected.stations.at(-1),direction=$('#service-direction');direction.innerHTML=selected.loop?`<option value="forward">내선 순환 · ${escapeHtml(first.ja)} 출발</option><option value="reverse">외선 순환 · ${escapeHtml(first.ja)} 출발</option>`:`<option value="forward">${escapeHtml(first.ja)} → ${escapeHtml(last.ja)}</option><option value="reverse">${escapeHtml(last.ja)} → ${escapeHtml(first.ja)}</option>`;
  const direct=throughSpec(selected),field=$('#through-service-fieldset'),destination=$('#through-destination');field.hidden=patterns.length>0||!direct;if(direct&&!patterns.length){destination.innerHTML=direct.allowedDestinations.map(name=>`<option value="${escapeHtml(name)}">${escapeHtml(name)}</option>`).join('');field.querySelector('[name="directService"][value="off"]').checked=true}
  configureJourneyPicker();
  go('game-setup')
}
async function chooseRoute(id){let route=routes.find(r=>r.id===id);if(!route&&dataLoading){pendingRouteId=id;toast('철도 데이터를 불러오는 중입니다. 잠시만 기다려 주세요.');return false}if(!route){console.warn('Line not found:',id);toast('선택한 노선을 찾을 수 없습니다. 데이터를 다시 불러와 주세요.');return false}if(route.lazy){toast(`${route.line.ko} 실제 역·선형을 불러오는 중입니다.`);try{const hydrated=railDataRepository.resolveRoute(await hydrateRailLine(route)),index=builtin.findIndex(item=>item.id===id);if(index>=0)builtin[index]=hydrated;refreshRoutes();route=routes.find(item=>item.id===id)}catch(error){console.error('Nationwide line load failed:',error);toast('이 노선의 상세 데이터를 불러오지 못했습니다.');return false}}selected=route;if(currentScreen!=='rail-map')go('rail-map');renderSelected();renderRoutes();return true}
function renderHome(){const recent=storage.recent().filter(record=>routes.some(route=>route.id===(record.lineId||record.routeId)));document.querySelectorAll('#feature-viewport [data-feature-route]').forEach((button,index)=>{const route=routes.find(item=>item.id===button.dataset.featureRoute),card=button.closest('article'),slot=card?.querySelector('.feature-number');if(!route||!card)return;if(slot){slot.innerHTML=lineBadgeMarkup(route);slot.hidden=!slot.innerHTML}const operator=card.querySelector('[data-feature-operator]'),lineKo=card.querySelector('[data-feature-line-ko]'),lineSecondary=card.querySelector('[data-feature-line-secondary]'),stations=card.querySelector('[data-feature-stations]');if(operator)operator.innerHTML=`${operatorLogoMarkup(route,'feature-operator-logo')}<span>${escapeHtml(route.operator.ko)} · ${route.loop?'순환 운행':'도심 운행'}</span>`;if(lineKo)lineKo.textContent=route.line.ko;if(lineSecondary)lineSecondary.textContent=`${route.line.ja} · ${route.line.en}`;if(stations)stations.textContent=`${route.stations.length}개 역`;const dot=$$('[data-slide-to]')[index];if(dot)dot.setAttribute('aria-label',route.line.ko)});$('#recent-list').innerHTML=recent.length?recent.slice(0,3).map(record=>{const route=routes.find(item=>item.id===(record.lineId||record.routeId)),name=route?.line.ko||record.routeName||record.routeId;return`<button class="recent-chip" data-feature-route="${escapeHtml(record.routeId)}" style="--route-color:${record.color}">${route?operatorLogoMarkup(route,'recent-operator-logo')+lineBadgeMarkup(route):''}<span><b>${escapeHtml(name)}</b><small>${formatTime(record.elapsed)} · ${record.accuracy.toFixed(1)}%</small></span></button>`}).join(''):'<p class="muted">아직 운행 기록이 없습니다.</p>'}
function renderCustomLibrary(){const list=storage.routes(),target=$('#custom-route-library');target.innerHTML=list.length?list.map(r=>`<article class="library-card" style="--route-color:${r.lineColor}" data-library-route="${r.id}"><span class="library-code">${escapeHtml(r.code||'CT')} · ${r.stations.length} STATIONS</span><h3>${escapeHtml(r.line.ko)}</h3><p>${escapeHtml(r.line.ja)} · ${escapeHtml(r.line.en)}</p><footer><button class="btn primary" data-library-play>PLAY</button><button class="btn ghost" data-library-edit>EDIT</button><button class="btn text" data-library-delete aria-label="${escapeHtml(r.line.ko)} 삭제">×</button></footer></article>`).join(''):`<div class="library-empty"><b>아직 만든 노선이 없습니다.</b><p>첫 노선을 만들고 원하는 역 순서로 달려보세요.</p><button class="btn primary" data-action="custom-new">＋ CREATE NEW ROUTE</button></div>`}
function showResult(result){const isRecord=storage.saveResult(result);$('#result-operator-logo').innerHTML=operatorLogoMarkup(result.route,'result-operator-logo-asset');$('#result-line-badge').innerHTML=lineBadgeMarkup(result.route);$('#result-route').textContent=`${result.route.line.ja} · ${result.route.line.ko} · ${result.route.operator.ko}`;$('#result-time').textContent=formatTime(result.elapsed);$('#result-accuracy').textContent=`${result.accuracy.toFixed(1)}%`;$('#result-cpm').textContent=`${result.cpm} 타/min`;$('#result-errors').textContent=result.errors;$('#result-combo').textContent=result.maxCombo;$('#result-wpm').textContent=result.wpm;$('#record-notice').hidden=!isRecord;go('result')}
const game=new Game({onFinish:showResult,onQuit:()=>go('select')});
const editor=new RouteEditor({onRoutesChanged:()=>{refreshRoutes();renderCustomLibrary()},onPlay:openSetup,onSaved:()=>go('custom-list')});
let currentScreen=document.body.dataset.currentScreen||'home';
window.addEventListener('trt:screenchange',e=>{const name=e.detail.name;if(currentScreen==='game'&&name!=='game')game?.stop(false);currentScreen=name;if(name==='rail-map')renderRoutes();if(name==='game-setup')configureExplicitDirections();if(name==='records')renderStats();if(name==='home')renderHome();if(name==='custom-list')renderCustomLibrary();if(name==='custom-editor')editor.activate()});
$('#setup-form').addEventListener('submit',applyExplicitDirection,true);
$('#service-options').addEventListener('change',event=>{const input=event.target.closest('[name="service"]');if(!input)return;const pattern=servicePatternsForRoute(selected?.id).find(item=>item.id===input.value);if(pattern?.directionId)$('#service-direction').value=pattern.directionId});
document.querySelector('.country-switch').addEventListener('click',async event=>{const button=event.target.closest('[data-country]');if(!button||!isCountryEnabled(button.dataset.country)||button.dataset.country===countryId)return;countryId=button.dataset.country;localStorage.setItem('trt-country',countryId);transportGroup='all';category='all';regionFilter='all';operatorFilter='all';selected=null;selectedGroup=null;applyCountryUi();refreshCountryCopy();await reloadRailData();renderTransportFilters();renderOperatorFilters();renderRoutes();refreshFeatureCounts();renderSelected();toast(countryId==='kr'?'대한민국 교통 데이터로 전환했습니다.':'일본 철도 데이터로 전환했습니다.')});
$('#transport-mode-tabs').addEventListener('click',event=>{const button=event.target.closest('[data-transport-group]');if(!button)return;transportGroup=button.dataset.transportGroup;category='all';regionFilter='all';operatorFilter='all';routeRenderLimit=96;renderTransportFilters();renderOperatorFilters();renderRoutes()});
$('#region-tabs').addEventListener('click',event=>{const button=event.target.closest('[data-region]');if(!button)return;regionFilter=button.dataset.region;category='all';operatorFilter='all';routeRenderLimit=96;renderTransportFilters();renderOperatorFilters();renderRoutes()});
$('#category-tabs').addEventListener('click',e=>{if(!e.target.dataset.category)return;category=e.target.dataset.category;routeRenderLimit=96;$$('button',$('#category-tabs')).forEach(b=>b.classList.toggle('active',b===e.target));renderRoutes()});
$('#operator-filters').addEventListener('click',e=>{const button=e.target.closest('[data-operator]');if(!button)return;operatorFilter=button.dataset.operator;routeRenderLimit=96;$$('button',$('#operator-filters')).forEach(item=>item.classList.toggle('active',item===button));renderRoutes()});
$('#route-search').addEventListener('input',()=>{routeRenderLimit=96;renderRoutes()});
$('#route-grid').addEventListener('click',e=>{if(e.target.closest('[data-route-more]')){routeRenderLimit+=96;renderRoutes();return}const group=e.target.closest('[data-route-group]');if(group){selected=null;selectedGroup=group.dataset.routeGroup;renderSelected();renderRoutes();return}const random=e.target.closest('[data-random-route]');if(random){const playable=filteredRoutes();if(playable.length)chooseRoute(playable[Math.floor(Math.random()*playable.length)].id);return}const card=e.target.closest('[data-route]');if(card){selectedGroup=null;chooseRoute(card.dataset.route)}});
$('#selected-line-preview').addEventListener('click',e=>{const branch=e.target.closest('[data-route]');if(branch){selectedGroup=null;chooseRoute(branch.dataset.route);return}if(e.target.closest('[data-selected-play]')&&selected)openSetup(selected)});
$('#clear-route-selection').addEventListener('click',()=>{selected=null;selectedGroup=null;renderSelected();renderRoutes()});
document.addEventListener('click',e=>{const create=e.target.closest('[data-action="custom-new"]');if(create){editor.createNew();go('custom-editor');return}const featured=e.target.closest('[data-feature-route]');if(featured){chooseRoute(featured.dataset.featureRoute);return}const card=e.target.closest('[data-library-route]');if(!card)return;const route=storage.routes().find(r=>r.id===card.dataset.libraryRoute);if(!route)return;if(e.target.closest('[data-library-play]'))openSetup(route);else if(e.target.closest('[data-library-edit]')){editor.loadRoute(route);go('custom-editor')}else if(e.target.closest('[data-library-delete]')&&confirm('이 노선을 삭제할까요?')){storage.deleteRoute(route.id);refreshRoutes();renderCustomLibrary();toast('노선을 삭제했습니다.')}});
$('#setup-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target),settings=storage.settings(),stationLabel=['ja','ja-romaji'].includes(settings.stationLabel)?settings.stationLabel:'ja',direct=throughSpec(selected),patternId=String(data.get('service')||''),patterns=servicePatternsForRoute(selected.id),journeys=serviceJourneysForRoute(selected.id);let resolved=null;try{resolved=journeys.length?resolveServiceJourney({baseRoute:selected,originStationId:String(data.get('journeyOrigin')||''),destinationStationId:String(data.get('journeyDestination')||''),trainTypeId:String(data.get('journeyTrainType')||''),getRoute:id=>builtin.find(route=>route.id===id)}):resolveServiceSelection({baseRoute:selected,servicePatternId:patterns.some(item=>item.id===patternId)?patternId:null,legacyServiceId:patternId,directionId:$('#service-direction').value,getRoute:id=>builtin.find(route=>route.id===id)})}catch(error){console.error('Service journey resolution failed:',error);return toast(`운행계통 오류: ${error.message}`)}lastRunRoute=data.get('directService')==='on'&&direct&&!patterns.length?buildThroughRoute(direct):resolved.route;if(!lastRunRoute)return toast('직결운행 데이터를 준비하지 못했습니다.');lastOptions={mode:data.get('mode'),inputMode:data.get('inputMode')||'shadowing',difficulty:data.get('difficulty'),service:resolved.service?.id||patternId,direction:resolved.direction,display:'ja',input:'ko',stationAdvance:data.get('stationAdvance')||settings.stationAdvance,mapMode:$('#game-map-mode').value,stationLabel,mapLabels:settings.mapLabels,motion:settings.motion,reducedMotion:settings.reducedMotion,sound:settings.sound,serviceJourney:resolved.journey||null,serviceJourneyId:resolved.journeyId||null,servicePattern:resolved.pattern,trainType:resolved.trainType,destinationStationId:resolved.destinationStationId,throughServiceId:resolved.pattern?.throughServiceId||lastRunRoute.throughService?.id||null,trainTypeContexts:resolved.trainTypeContexts||[]};if(lastRunRoute.dataKind==='throughService'&&!resolved.pattern){lastOptions.service='local';lastOptions.direction='forward'}$('#map-view-toggle').textContent=lastOptions.mapMode==='geographic'?'SCHEMATIC':'GEOGRAPHIC';if(game.start(lastRunRoute,lastOptions)){go('game');game.focusInput()}});
$('#retry-game').addEventListener('click',()=>{if(game.start(lastRunRoute||selected,lastOptions)){go('game');game.focusInput()}});
$('#map-view-toggle').addEventListener('click',()=>game.toggleMapMode());
$('#settings-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),settings={...storage.settings(),theme:f.get('theme'),stationAdvance:f.get('stationAdvance'),display:'ja',input:'ko',mapMode:f.get('mapMode'),stationLabel:f.get('stationLabel'),mapLabels:f.get('mapLabels'),sound:f.get('sound')==='on',motion:f.get('motion')==='on',reducedMotion:f.get('reducedMotion')==='on'};storage.saveSettings(settings);applyTheme(settings.theme);document.body.classList.toggle('reduce-motion',settings.reducedMotion);toast('설정을 저장했습니다.')});
const settings=storage.settings(),sf=$('#settings-form').elements;sf.theme.value=settings.theme;sf.stationAdvance.value=settings.stationAdvance;sf.mapMode.value=settings.mapMode;sf.stationLabel.value=['ja','ja-romaji'].includes(settings.stationLabel)?settings.stationLabel:'ja';sf.mapLabels.value=settings.mapLabels;sf.sound.checked=settings.sound;sf.motion.checked=settings.motion;sf.reducedMotion.checked=settings.reducedMotion;applyTheme(settings.theme);document.body.classList.toggle('reduce-motion',settings.reducedMotion);matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if(storage.settings().theme==='system')applyTheme('system')});
$('#game-theme-toggle').addEventListener('click',()=>{const current=document.documentElement.dataset.theme,next=current==='dark'?'light':'dark',updated={...storage.settings(),theme:next};storage.saveSettings(updated);sf.theme.value=next;applyTheme(next);game.refreshMap()});
const updateClock=()=>$('#clock').textContent=new Intl.DateTimeFormat('ko-KR',{hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date());updateClock();setInterval(updateClock,1000);
function setFeature(next){featureIndex=(next+3)%3;$$('[data-feature-index]').forEach((card,i)=>card.classList.toggle('active',i===featureIndex));$$('[data-slide-to]').forEach((dot,i)=>dot.classList.toggle('active',i===featureIndex));$('#feature-counter').textContent=`0${featureIndex+1} / 03`}
function restartFeatureTimer(){clearInterval(featureTimer);if(matchMedia('(prefers-reduced-motion: reduce)').matches||document.body.classList.contains('reduce-motion'))return;featureTimer=setInterval(()=>setFeature(featureIndex+1),7000)}
document.querySelector('.feature-controls').addEventListener('click',e=>{const direction=e.target.closest('[data-slide]')?.dataset.slide,to=e.target.closest('[data-slide-to]')?.dataset.slideTo;if(direction)setFeature(featureIndex+(direction==='next'?1:-1));if(to!==undefined)setFeature(+to);restartFeatureTimer()});
$('#feature-viewport').addEventListener('mouseenter',()=>clearInterval(featureTimer));$('#feature-viewport').addEventListener('mouseleave',restartFeatureTimer);restartFeatureTimer();
$('#library-import').addEventListener('change',async e=>{await editor.import(e.target.files[0]);e.target.value='';renderCustomLibrary();go('custom-editor')});
initAuth(storage);applyCountryUi();refreshCountryCopy();renderHome();renderCustomLibrary();refreshRoutes();if(currentScreen==='records')renderStats();if(['game','game-setup','result'].includes(currentScreen)){window.TRTNavigation?.showScreen('rail-map',{history:'replace'});toast('노선을 먼저 선택해 주세요.')}
async function reloadRailData(){const summary=$('#data-summary');dataLoading=true;summary.classList.remove('error');summary.textContent=`${countryId==='kr'?'대한민국 대중교통':'일본 전국 철도'} 카탈로그를 불러오는 중...`;try{const loaded=await loadTransportData(countryId);railDataRepository.configure({operators:loaded.operators,lines:loaded.lines,stations:loaded.stations,assets:loaded.assets});builtin=loaded.lines.map(route=>railDataRepository.resolveRoute(route));stations=[...railDataRepository.stations.values()].map(station=>({id:station.id,stationMasterId:station.id,sourceStationId:station.id,ja:station.names.ja,kana:station.names.kana,ko:station.names.ko,romaji:station.names.en,latitude:station.coordinates.lat,longitude:station.coordinates.lng}));stations=stations.filter(station=>FEATURE_FLAGS.visibleJapanRegion!=='tokyo-area'||!globalThis.TRT_TOKYO_AREA||countryId==='kr'||globalThis.TRT_TOKYO_AREA.stationIds.includes(station.id));editor.setStationMaster(stations);refreshRoutes();renderHome();summary.innerHTML=countryId==='kr'?`대한민국 1차 데이터 · ${builtin.length}개 대표 노선 · 상세 데이터는 노선 선택 시 로드 · 선형 미확보 노선도 정차 순서 타이핑 가능`:`일본 전국 ${routes.length}개 · JR ${routes.filter(r=>r.category==='jr').length} · 지하철 ${routes.filter(r=>r.category==='subway').length} · 사철 ${routes.filter(r=>r.category==='private').length} · 제3섹터 ${routes.filter(r=>r.category==='third-sector').length} · 트램 ${routes.filter(r=>r.category==='tram').length} · 신칸센 ${routes.filter(r=>r.category==='shinkansen').length}`;dataLoading=false;if(pendingRouteId){const id=pendingRouteId;pendingRouteId=null;chooseRoute(id)}return loaded}catch(error){console.error('App transport data initialization failed:',error);builtin=[];editor.setStationMaster([]);refreshRoutes();renderHome();dataLoading=false;summary.classList.add('error');summary.innerHTML='교통 데이터를 불러오지 못했습니다. <button data-retry-data>다시 시도</button>';return null}}
document.addEventListener('click',e=>{if(e.target.closest('[data-retry-data]'))reloadRailData()});
function runSanityChecks(){console.assert(routes.length>0,'Transport data must contain routes');if(countryId==='jp'){console.assert(routes.some(line=>line.id==='line-11302'),'Yamanote line is required');console.assert(routes.some(line=>line.id==='line-28001'),'Ginza line is required')}else console.assert(routes.some(line=>line.id==='kr-seoul-line-2'),'Seoul Line 2 is required');console.assert(routes.every(line=>line.lazy||(Array.isArray(line.stations)&&line.stations.length>=2)),'Every visible route must be playable or lazy-loadable')}
await reloadRailData();refreshFeatureCounts();if(['localhost','127.0.0.1'].includes(location.hostname))runSanityChecks();
