import{$,$$,toast}from'./utils.js';
const SESSION_KEY='trt:supabase.session.v1';
export class AuthClient{
  constructor(storage){this.storage=storage;this.config=globalThis.TRT_SUPABASE_CONFIG||{};this.session=this.readSession();this.mode='login';this.bind();this.setMode('login');this.render()}
  get configured(){return /^https:\/\/.+\.supabase\.co$/i.test(this.config.url||'')&&String(this.config.anonKey||'').length>20}
  readSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
  saveSession(session){this.session=session||null;try{session?localStorage.setItem(SESSION_KEY,JSON.stringify(session)):localStorage.removeItem(SESSION_KEY)}catch{}this.render()}
  headers(token){return{'Content-Type':'application/json',apikey:this.config.anonKey,Authorization:`Bearer ${token||this.config.anonKey}`}}
  async request(path,body){if(!this.configured)throw new Error('Supabase 공개 설정이 필요합니다.');const response=await fetch(`${this.config.url}${path}`,{method:'POST',headers:this.headers(),body:JSON.stringify(body)}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.msg||data.error_description||data.message||'인증 요청에 실패했습니다.');return data}
  bind(){document.addEventListener('click',event=>{if(event.target.closest('[data-auth-open]')){$('#auth-dialog').hidden=false;this.renderConfigStatus();$('#auth-email').focus()}const modeButton=event.target.closest('[data-auth-mode]');if(modeButton)this.setMode(modeButton.dataset.authMode);if(event.target.closest('[data-auth-close]'))$('#auth-dialog').hidden=true;if(event.target.closest('[data-auth-logout]'))this.logout()});$('#auth-form')?.addEventListener('submit',event=>this.submit(event))}
  setMode(mode){this.mode=mode==='signup'?'signup':'login';const form=$('#auth-form');if(!form)return;form.elements.mode.value=this.mode;$$('[data-auth-mode]',form).forEach(button=>{const active=button.dataset.authMode===this.mode;button.classList.toggle('active',active);button.setAttribute('aria-selected',String(active))});$$('[data-signup-field]',form).forEach(field=>{field.hidden=this.mode!=='signup';const input=field.querySelector('input');if(input)input.required=this.mode==='signup'});form.elements.password.autocomplete=this.mode==='signup'?'new-password':'current-password';form.querySelector('[type="submit"]').textContent=this.mode==='signup'?'회원가입':'로그인';this.clearError()}
  clearError(){const target=$('#auth-error');if(target){target.hidden=true;target.textContent=''}}
  showError(message){const target=$('#auth-error');if(target){target.textContent=message;target.hidden=false}toast(message)}
  renderConfigStatus(){const target=$('#auth-config-status'),submit=$('#auth-form')?.querySelector('[type="submit"]');if(target)target.textContent=this.configured?'안전한 계정 연결이 준비되었습니다.':'계정 연결 설정이 없어 현재는 게스트 플레이만 사용할 수 있습니다.';if(submit){submit.disabled=!this.configured;submit.title=this.configured?'':'배포 설정에 Supabase 공개 URL과 anon key가 필요합니다.'}}
  async submit(event){event.preventDefault();this.clearError();const form=new FormData(event.target),mode=form.get('mode'),email=String(form.get('email')||'').trim(),password=String(form.get('password')||''),passwordConfirm=String(form.get('passwordConfirm')||''),nickname=String(form.get('nickname')||'철도러').trim();if(!this.configured)return this.showError('계정 연결이 아직 설정되지 않았습니다. 게스트 플레이를 이용해 주세요.');if(mode==='signup'&&password!==passwordConfirm)return this.showError('비밀번호 확인이 일치하지 않습니다.');const submit=event.target.querySelector('[type="submit"]');submit.disabled=true;try{const path=mode==='signup'?'/auth/v1/signup':'/auth/v1/token?grant_type=password',body=mode==='signup'?{email,password,data:{nickname}}:{email,password},data=await this.request(path,body);if(data.access_token){this.saveSession(data);$('#auth-dialog').hidden=true;toast(mode==='signup'?'회원가입과 로그인이 완료되었습니다.':'로그인했습니다.');await this.migrateLocal()}else toast('확인 이메일을 전송했습니다.')}catch(error){this.showError(error.message)}finally{submit.disabled=false}}
  async logout(){try{if(this.configured&&this.session?.access_token)await fetch(`${this.config.url}/auth/v1/logout`,{method:'POST',headers:this.headers(this.session.access_token)})}catch(error){console.warn('Remote logout deferred:',error)}finally{this.saveSession(null);toast('로그아웃했습니다.')}}
  async migrateLocal(){if(!this.session?.access_token)return;const userId=this.session.user?.id;if(!userId)return;const payload={user_id:userId,records:this.storage.records(),custom_routes:this.storage.routes(),updated_at:new Date().toISOString()};try{await fetch(`${this.config.url}/rest/v1/player_profiles?on_conflict=user_id`,{method:'POST',headers:{...this.headers(this.session.access_token),Prefer:'resolution=merge-duplicates'},body:JSON.stringify(payload)})}catch(error){console.warn('Cloud migration deferred:',error)}}
  render(){const user=this.session?.user,nickname=user?.user_metadata?.nickname||user?.email?.split('@')[0]||'게스트';$$('[data-auth-state]').forEach(node=>{node.innerHTML=user?`<span class="auth-avatar">${nickname.slice(0,1).toUpperCase()}</span><b>${nickname}</b><button data-auth-logout>로그아웃</button>`:`<button data-auth-open>로그인 · 회원가입</button><small>게스트</small>`});this.renderConfigStatus()}
}
export function initAuth(storage){return new AuthClient(storage)}
