import{$,escapeHtml,formatTime,toast}from'./utils.js';
import{TypingController}from'./typing.js';
import{TypingStatistics}from'./statistics-engine.js';
import{renderGameMap,setTrainTypingProgress}from'./route-renderer.js';
import{lineBadgeMarkup,lineBadgeMeta}from'./line-badge.js';
import{resolveStationSignTemplate}from'./station-sign-templates.js';
import{resolvePlayableRoute}from'./route-integrity.js';
export class Game{
  constructor({onFinish,onQuit}){
    this.onFinish=onFinish;this.onQuit=onQuit;this.timer=null;this.moveTimer=null;this.phase='IDLE';this.stats=new TypingStatistics();
    this.typing=new TypingController($('#typing-input'),{onChange:value=>this.onInput(value),onSubmit:()=>this.correct()});
    $('#pause-button').addEventListener('click',()=>this.togglePause());$('#resume-game').addEventListener('click',()=>this.togglePause(false));$('#quit-game').addEventListener('click',()=>this.stop(true));$('#next-station-button').addEventListener('click',()=>this.advance());
    $('#screen-game').addEventListener('pointerdown',event=>{if(this.phase==='TYPING'&&!event.target.closest('button,a,select,input,textarea'))this.focusInput()});
    document.addEventListener('keydown',event=>{if(!$('#screen-game').classList.contains('active'))return;if(event.key==='Escape'){event.preventDefault();this.togglePause()}if(event.code==='Space'&&this.phase==='CORRECT_WAITING'&&!this.typing.isComposing()){event.preventDefault();this.advance()}})
  }
  start(route,options={}){
    this.stop(false);if(!route||!Array.isArray(route.stations)||route.stations.length<2){console.error('Cannot start invalid line:',route?.id||route);toast('플레이하려면 역이 2개 이상인 노선이 필요합니다.');return false}
    this.route=route;this.options={mode:'complete',difficulty:'normal',display:'ja',input:'ko',direction:'forward',stationAdvance:'auto',mapMode:'geographic',stationLabel:'ja',mapLabels:'normal',motion:true,...options};this.service=route.services?.find(service=>service.id===this.options.service)||route.services?.find(service=>service.id==='local')||route.services?.[0]||{id:'local',nameJa:'各駅停車',nameKo:'각역정차',nameEn:'Local',stops:route.stations.map(station=>station.id)};
    try{this.resolvedRoute=resolvePlayableRoute(route,{direction:this.options.direction,service:this.service})}catch(error){console.error('Route integrity blocked game start:',error);toast(`노선 무결성 오류: ${error.message}`);return false}
    this.sessionId=(this.sessionId||0)+1;this.serviceStations=this.resolvedRoute.stations;this.serviceStops=new Set(this.serviceStations.map(station=>station.id));this.mapRoute={...route,stations:this.resolvedRoute.stations,geometry:this.resolvedRoute.geometry,directedSegments:this.resolvedRoute.segments,renderKey:`${this.resolvedRoute.renderKey}::session-${this.sessionId}`};this.sequence=this.makeSequence();this.index=0;this.boarding=true;this.typedStationIds=[];this.visitedStationIds=[];this.errors=0;this.combo=0;this.maxCombo=0;this.started=performance.now();this.stats.reset(this.started);this.pausedTotal=0;this.pausedAt=0;this.finished=false;this.paused=false;this.phase='TYPING';
    const sign=$('#station-sign'),template=resolveStationSignTemplate(route);sign.dataset.signStyle=template.style;sign.dataset.templateFamily=template.family;sign.dataset.templateSource=template.referenceSource;this.applyActiveBrand(this.sequence[0]);$('#station-service-footer').textContent=`${this.service.nameKo||'각역정차'} 운행`;$('#game-service-name').textContent=`${this.service.nameKo}${this.service.nameJa?` · ${this.service.nameJa}`:''}`;const origin=this.sequence[0],destination=this.sequence.at(-1);$('#service-origin-ja').textContent=origin.ja;$('#service-origin-ko').textContent=origin.ko;$('#service-destination-ja').textContent=destination.ja;$('#service-destination-ko').textContent=destination.ko;$('#service-stop-count').textContent=`${this.sequence.length}개 역`;$('#service-route-summary').textContent=`${route.line.ko} · ${this.service.nameKo}`;$('#service-direction-summary').textContent=`${origin.ko} → ${destination.ko}`;this.showDeparture();this.renderStation();this.updateHud();this.timer=setInterval(()=>this.tick(),50);this.typing.focus();return true
  }
  makeSequence(){const base=[...this.serviceStations];if(this.options.mode==='random')return Array.from({length:100},()=>base[Math.floor(Math.random()*base.length)]);if(this.options.mode==='endless')return Array.from({length:500},(_,i)=>base[i%base.length]);return base}
  focusInput(){if(!this.paused&&this.phase==='TYPING')this.typing.focus()}
  answerValues(station){return[station.ko,...(station.koAliases||[])]}
  routeIndex(station){return Math.max(0,this.mapRoute.stations.findIndex(item=>item.id===station?.id))}
  currentStation(){return this.sequence?.[this.index]||null}
  targetStation(){return this.boarding?this.sequence?.[0]||null:this.sequence?.[this.index+1]||null}
  activeSegment(){return this.boarding?null:this.resolvedRoute?.segments?.[this.index]||null}
  mapOptions(){const current=this.currentStation(),previous=this.sequence[this.index-1],target=this.targetStation();return{mapMode:this.options.mapMode,stationLabel:'ja-ko',mapLabels:this.options.mapLabels,motion:this.options.motion&&!this.options.reducedMotion,serviceStops:[...this.serviceStops],previousRouteIndex:this.routeIndex(previous||current),nextRouteIndex:this.routeIndex(target||current)}}
  syncDebug(){const current=this.currentStation(),target=this.targetStation(),segment=this.activeSegment();globalThis.__TRT_GAME_DEBUG__={phase:this.phase,boarding:this.boarding,currentIndex:this.index,currentStationId:current?.id||null,currentStationKo:current?.ko||null,targetStationId:target?.id||null,targetStationKo:target?.ko||null,activeSegmentFrom:segment?.fromStationId||null,activeSegmentTo:segment?.toStationId||null,answer:this.typing.targets?.[0]||null,typedStationIds:[...this.typedStationIds],visitedStationIds:[...this.visitedStationIds]};document.body.dataset.gamePhase=this.phase;document.body.dataset.gameBoarding=String(this.boarding);document.body.dataset.currentStationId=current?.id||'';document.body.dataset.targetStationId=target?.id||''}
  activeRoute(station){return station?.segment||this.route}
  applyActiveBrand(station){const active=this.activeRoute(station),sign=$('#station-sign'),operatorKo=active.operator.ko||'MISSING_KOREAN_NAME',lineKo=active.line.ko||'MISSING_KOREAN_NAME';sign.style.setProperty('--route-color',active.lineColor);$('#station-operator-mark').innerHTML=active.operatorAsset?`<img class="station-operator-logo" src="${escapeHtml(active.operatorAsset.asset)}" alt="${escapeHtml(active.operatorAsset.label)} 로고">`:`<span>${escapeHtml(operatorKo)}</span>`;$('#station-line-label').innerHTML=`${lineBadgeMarkup(active,'station-line-symbol')}<b>${escapeHtml(lineKo)}</b>${active.line.ja?`<small>${escapeHtml(active.line.ja)}</small>`:''}`;$('#game-operator').textContent=operatorKo;$('#game-line-name').textContent=lineKo;$('#station-badge').style.setProperty('--route-color',active.lineColor)}
  renderKoreanProgress(value='',state='empty'){const target=$('#ko-progress'),answer=String(this.answerValues(this.targetStation())[0]||'').normalize('NFC'),typed=Array.from(String(value).normalize('NFC')),letters=Array.from(answer),matches=letters.findIndex((letter,index)=>typed[index]!==undefined&&typed[index]!==letter),done=matches<0?Math.min(typed.length,letters.length):matches;if(target.children.length!==letters.length){target.replaceChildren(...letters.map(()=>{const cell=document.createElement('span');cell.className='input-cell';cell.textContent='';return cell}));this.fitProgressCells(letters.length)}[...target.children].forEach((cell,index)=>{const text=typed[index]||'';if(cell.textContent!==text)cell.textContent=text;cell.classList.toggle('done',index<done);cell.classList.toggle('wrong',matches===index&&state==='wrong')})}
  fitProgressCells(count){const target=$('#ko-progress');cancelAnimationFrame(this.cellFitFrame);this.cellFitFrame=requestAnimationFrame(()=>{const width=Math.max(1,target.clientWidth),gap=count>=15?1:count>=10?3:count>=6?5:7,size=Math.max(11,Math.min(32,(width-gap*Math.max(0,count-1))/Math.max(1,count)));target.style.setProperty('--char-count',Math.max(1,count));target.style.setProperty('--cell-gap',`${gap}px`);target.style.setProperty('--cell-size',`${size}px`);target.dataset.lengthClass=count>=15?'compact':count>=10?'small':count>=6?'medium':'large'})}
  fitPrompt(){for(const el of [$('#prompt-main'),$('#prompt-ko')]){el.style.fontSize='';let size=parseFloat(getComputedStyle(el).fontSize);while(el.scrollWidth>el.clientWidth&&size>14){size-=2;el.style.fontSize=`${size}px`}}}
  renderStation(){
    const current=this.currentStation(),station=this.targetStation();if(!station)return this.finish();this.phase='TYPING';const hard=this.options.difficulty==='hard'||this.options.mode==='order',following=this.boarding?this.sequence[1]:this.sequence[this.index+2],previous=this.boarding?null:current,sign=$('#station-sign');sign.classList.remove('sign-enter');void sign.offsetWidth;sign.classList.add('sign-enter');
    this.applyActiveBrand(station);$('#prompt-main').textContent=station.ja;const memory=this.options.inputMode==='memory';$('#prompt-ko').textContent=memory?'정답 비공개':station.ko;$('#prompt-ko').classList.toggle('memory-hidden',memory);$('#prompt-kana').textContent=hard?'••••••':station.kana;$('#prompt-sub').textContent=hard?'한국어 역명을 입력하세요':station.romaji;const badge=$('#station-badge'),officialCode=station.hasOfficialStationCode?station.officialCode:'';badge.textContent=officialCode;badge.hidden=!officialCode;$('#station-context').textContent=this.boarding?'출발역 입력':'다음역 입력';$('#previous-station-name').textContent=previous?.ko||'출발역';$('#previous-station-romaji').textContent=previous?`${previous.ja} · ${previous.romaji}`:'ORIGIN';$('#next-station-name').textContent=following?.ko||'종착역';$('#next-station-romaji').textContent=following?`${following.ja} · ${following.romaji}`:'TERMINAL';$('#next-station').textContent=station.ko;$('#error-count').textContent=this.errors;this.fitPrompt();this.renderKoreanProgress();
    const input=$('#typing-input');input.readOnly=false;input.disabled=this.paused;input.closest('.typing-box').classList.remove('waiting');$('#next-station-button').hidden=true;$('#input-status').textContent='TYPE';$('#input-status').style.color='';this.typing.setTarget(this.answerValues(station));renderGameMap(this.mapRoute,this.routeIndex(current),this.mapOptions());this.syncDebug();if(!this.paused)this.typing.focus()
  }
  onInput({state,value}){if(this.paused||this.phase!=='TYPING')return;const started=performance.now();this.renderKoreanProgress(value,state);const target=Array.from(this.answerValues(this.targetStation())[0]||''),typed=Array.from(value||'');let prefix=0;while(prefix<target.length&&typed[prefix]===target[prefix])prefix++;setTrainTypingProgress(this.boarding?0:target.length?prefix/target.length:0,this.options.motion&&!this.options.reducedMotion);const before=this.stats.mistakeUnits;this.stats.observe({value,state});this.errors=this.stats.mistakeUnits;if(this.errors>before){this.combo=0;$('#error-count').textContent=this.errors}$('#input-status').textContent=state==='wrong'?'CHECK':state==='typing'?`TYPING ${Math.round(prefix/Math.max(1,target.length)*100)}%`:'TYPE';$('#input-status').style.color=state==='wrong'?'#d93f3f':'';document.body.dataset.typingUpdateMs=(performance.now()-started).toFixed(2);this.updateHud()}
  correct(){
    if(this.paused||this.finished||this.phase!=='TYPING')return;const station=this.targetStation();if(!station)return;this.phase='ARRIVING';this.stats.complete(this.answerValues(station)[0]||'');this.typedStationIds.push(station.id);this.combo++;this.maxCombo=Math.max(this.maxCombo,this.combo);const manual=this.options.stationAdvance==='space';setTrainTypingProgress(this.boarding?0:1,this.options.motion&&!this.options.reducedMotion);$('#typing-input').readOnly=true;$('#typing-input').closest('.typing-box').classList.add('waiting');$('#input-status').textContent=manual?'SPACE NEXT':this.boarding?'DEPARTING':'ARRIVING';$('#next-station-button').hidden=!manual;this.phase=manual?'CORRECT_WAITING':'ARRIVING';this.playTone();this.updateHud();this.syncDebug();if(!manual)this.moveTimer=setTimeout(()=>this.advance(),150)
  }
  advance(){
    if(this.finished||this.paused||!['CORRECT_WAITING','ARRIVING'].includes(this.phase))return;this.phase='MOVING';$('#next-station-button').hidden=true;const arrived=this.targetStation();if(!arrived)return this.finish();if(this.boarding){this.boarding=false;const current=this.currentStation();renderGameMap(this.mapRoute,this.routeIndex(current),this.mapOptions());this.updateHud();this.syncDebug();this.moveTimer=setTimeout(()=>this.renderStation(),20);return}this.advanceToNextStation(arrived);const current=this.currentStation();renderGameMap(this.mapRoute,this.routeIndex(current),this.mapOptions());this.updateHud();this.syncDebug();if((this.options.mode==='random'&&this.elapsed()>=60000)||!this.targetStation())return this.finish();this.moveTimer=setTimeout(()=>this.renderStation(),20)
  }
  advanceToNextStation(arrived){if(this.phase!=='MOVING')throw new Error('Invalid station advance');const expected=this.targetStation();if(!expected||expected.id!==arrived?.id)throw new Error('Typed station and arrival station mismatch');this.index+=1;const current=this.currentStation();if(current?.id!==arrived.id)throw new Error('Station index advanced to an unexpected station');this.visitedStationIds.push(arrived.id)}
  toggleMapMode(){this.options.mapMode=this.options.mapMode==='geographic'?'schematic':'geographic';$('#map-view-toggle').textContent=this.options.mapMode==='geographic'?'SCHEMATIC':'GEOGRAPHIC';const station=this.sequence[this.index];if(station)renderGameMap(this.mapRoute,this.routeIndex(station),this.mapOptions());return this.options.mapMode}
  refreshMap(){const station=this.sequence?.[this.index];if(station)renderGameMap(this.mapRoute,this.routeIndex(station),this.mapOptions())}
  showDeparture(){const overlay=$('#departure-overlay'),first=this.sequence[0],last=this.sequence.at(-1);overlay.style.setProperty('--route-color',this.route.lineColor);$('#departure-line').textContent=`${this.route.line.ko} · ${this.route.line.ja}`;$('#departure-service').textContent=`${this.service.nameKo} · ${this.service.nameJa}`;$('#departure-direction').textContent=`${first.ko} → ${last.ko} 방면`;overlay.hidden=false;clearTimeout(this.departureTimer);this.departureTimer=setTimeout(()=>{overlay.hidden=true;this.focusInput()},850)}
  playTone(){if(!this.options.sound)return;try{const context=new AudioContext(),osc=context.createOscillator(),gain=context.createGain();osc.frequency.value=720;gain.gain.setValueAtTime(.035,context.currentTime);gain.gain.exponentialRampToValueAtTime(.001,context.currentTime+.08);osc.connect(gain).connect(context.destination);osc.start();osc.stop(context.currentTime+.08)}catch{}}
  elapsed(){return performance.now()-this.started-this.pausedTotal-(this.paused?performance.now()-this.pausedAt:0)}
  tick(){if(!this.paused){if(this.options.mode==='random'&&this.elapsed()>=60000)return this.finish();this.updateHud()}}
  metrics(){const elapsed=Math.max(1,this.elapsed());return{elapsed,...this.stats.metrics(elapsed)}}
  updateHud(){const metrics=this.metrics(),completed=this.typedStationIds.length;$('#hud-time').textContent=formatTime(metrics.elapsed);$('#hud-progress').textContent=`${Math.min(completed,this.sequence.length)} / ${this.options.mode==='random'?'∞':this.sequence.length}`;$('#hud-cpm').textContent=Number.isFinite(metrics.cpm)?metrics.cpm:0;$('#hud-accuracy').textContent=`${metrics.accuracy.toFixed(1)}%`;$('#hud-combo').textContent=`×${this.combo}`}
  togglePause(force){if(this.finished)return;const next=force??!this.paused;if(next===this.paused)return;this.paused=next;$('#pause-overlay').hidden=!next;$('#typing-input').disabled=next;if(next)this.pausedAt=performance.now();else{this.pausedTotal+=performance.now()-this.pausedAt;if(this.phase==='ARRIVING')this.moveTimer=setTimeout(()=>this.advance(),100);if(this.phase==='TYPING')this.typing.focus()}}
  finish(){if(this.finished)return;this.finished=true;this.phase='FINISHED';clearInterval(this.timer);clearTimeout(this.moveTimer);this.timer=null;const expectedArrivals=this.options.mode==='complete'?this.sequence.slice(1).map(station=>station.id):[],expectedTyped=this.options.mode==='complete'?this.sequence.map(station=>station.id):[],routeIntegrity=this.options.mode!=='complete'||JSON.stringify(expectedArrivals)===JSON.stringify(this.visitedStationIds)&&JSON.stringify(expectedTyped)===JSON.stringify(this.typedStationIds);if(!routeIntegrity)console.error('ROUTE INTEGRITY ERROR',{expectedArrivals,visited:this.visitedStationIds,expectedTyped,typed:this.typedStationIds});this.syncDebug();const metrics=this.metrics();this.onFinish({...metrics,errors:this.errors,maxCombo:this.maxCombo,completed:this.typedStationIds.length,routeId:this.route.id,routeName:this.route.line.ko,color:this.route.lineColor,route:this.route,options:this.options,routeIntegrity,typedStationIds:[...this.typedStationIds],visitedStationIds:[...this.visitedStationIds]})}
  stop(notify=false){clearInterval(this.timer);clearTimeout(this.moveTimer);clearTimeout(this.departureTimer);this.timer=null;this.finished=true;this.phase='IDLE';this.paused=false;$('#pause-overlay').hidden=true;$('#departure-overlay').hidden=true;$('#typing-input').disabled=false;$('#typing-input').readOnly=false;if(notify)this.onQuit?.()}
}
