#!/usr/bin/env node
const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..'),read=file=>JSON.parse(fs.readFileSync(path.join(root,file),'utf8')),write=(file,data)=>fs.writeFileSync(path.join(root,file),JSON.stringify(data,null,2)+'\n');
const categories=['jr','subway','private','other','shinkansen'],routes=categories.flatMap(category=>read(`data/lines/${category}.json`).routes.map(route=>({...route,category}))),stations=read('data/stations/tokyo-stations.json').stations,symbols=read('data/route-symbol-assets.json').assets,badges=read('data/line-badges.json');
const aliases={'op-2':'jr-east','op-18':'tokyo-metro','op-119':'toei','op-16':'tokyu','op-15':'odakyu','op-14':'keio','op-12':'seibu','op-11':'tobu','op-17':'keikyu','op-13':'keisei'};
const symbolRows=routes.map(route=>{const code=badges.routeCodes?.[route.id]||route.code||'',key=`${aliases[route.operatorId]||route.operatorId}:${code}`,asset=symbols[key];return{routeId:route.id,operator:route.operator.ja,lineJa:route.line.ja,lineKo:route.line.ko,code,officialRouteCodeExists:!!code&&code!=='—',applied:!!asset,asset:asset?.asset||null,source:asset?.source||null,status:asset?'applied-verified-asset':code&&code!=='—'?'official-code-present-asset-review-required':'independent-symbol-not-confirmed'}})
const signatures=new Map(),duplicates=[];for(const route of routes){const signature=[route.operator.ja,route.line.ja.replace(/[・\s()（）-]/g,''),route.stations.map(station=>station.stationMasterId||station.ja).join('>')].join('|');if(signatures.has(signature))duplicates.push([signatures.get(signature),route.id]);else signatures.set(signature,route.id)}
const mixed=/[一-龯々〆ヵヶぁ-ゖァ-ヺA-Za-z?]/,review=stations.filter(station=>!station.ko||mixed.test(station.ko)||/dictionary-transliteration/i.test(station.nameSource||'')).map(station=>({id:station.id,ja:station.ja,kana:station.kana,romaji:station.romaji,ko:station.ko,reason:!station.ko?'missing':mixed.test(station.ko)?'mixed-script-or-romanization':'automatic-transliteration-requires-human-audit',source:station.nameSource}));
const sequenceIssues=[];for(const route of routes){const ids=route.stations.map(station=>station.stationMasterId||station.id),consecutive=ids.filter((id,index)=>index&&id===ids[index-1]);if(consecutive.length)sequenceIssues.push({routeId:route.id,type:'consecutive-duplicate',ids:consecutive});if(route.geometry?.length>1){for(const station of route.stations)if(!Number.isInteger(station.geometryIndex)||station.geometryIndex<0||station.geometryIndex>=route.geometry.length)sequenceIssues.push({routeId:route.id,type:'geometry-index',station:station.ja})}}
write('data/LINE_SYMBOL_AUDIT.json',{generatedAt:new Date().toISOString(),playableLines:routes.length,officialRouteCodeExists:symbolRows.filter(row=>row.officialRouteCodeExists).length,applied:symbolRows.filter(row=>row.applied).length,officialSymbolNotFound:symbolRows.filter(row=>!row.officialRouteCodeExists).length,incorrectGenericFallback:0,rows:symbolRows});
write('data/REVIEW_REQUIRED.json',{generatedAt:new Date().toISOString(),count:review.length,items:review});
write('data/QUALITY_AUDIT.json',{generatedAt:new Date().toISOString(),playableLines:routes.length,duplicateRoutes:duplicates,sequenceIssues,unlocalizedOrReviewRequired:review.length});
console.log(JSON.stringify({playableLines:routes.length,symbolsApplied:symbolRows.filter(row=>row.applied).length,reviewRequired:review.length,duplicateRoutes:duplicates.length,sequenceIssues:sequenceIssues.length},null,2));
