#!/usr/bin/env node
const fs=require('fs'),path=require('path'),crypto=require('crypto');
require('./build-line-workspaces');
require('./build-korea-data');
const root=path.resolve(__dirname,'..'),read=relative=>fs.readFileSync(path.join(root,relative),'utf8');
const write=(relative,value)=>{const target=path.join(root,relative),temporary=`${target}.tmp`;fs.writeFileSync(temporary,value);fs.renameSync(temporary,target)};
const categories=['jr','subway','private','other','shinkansen'];
const embedded={operators:JSON.parse(read('data/operators/operators.json')),stations:JSON.parse(read('data/stations/tokyo-stations.json')),lines:Object.fromEntries(categories.map(category=>[category,JSON.parse(read(`data/lines/${category}.json`))]))};
const nationwideIndex=JSON.parse(read('data/nationwide/index.json')),nationwideRoutes=Object.fromEntries((nationwideIndex.routes||[]).map(meta=>{const key=String(meta.lazySource).replace(/^\.\//,'');return[key,JSON.parse(read(key))]}));
const baseline=JSON.parse(read('data/RECOVERY_BASELINE.json')),sourceCounts={operators:embedded.operators.operators?.length||0,lines:categories.reduce((sum,category)=>sum+(embedded.lines[category].routes?.length||0),0),relations:categories.reduce((sum,category)=>sum+(embedded.lines[category].routes||[]).reduce((count,route)=>count+(route.stations?.length||0),0),0),nationwideLines:nationwideIndex.routes?.length||0,nationwideRouteFiles:Object.keys(nationwideRoutes).length};
const unsafe=[['operators',sourceCounts.operators,baseline.curated.operators],['lines',sourceCounts.lines,baseline.curated.lines],['relations',sourceCounts.relations,baseline.curated.lineStationRelations],['nationwideLines',sourceCounts.nationwideLines,baseline.nationwide.lines],['nationwideRouteFiles',sourceCounts.nationwideRouteFiles,baseline.nationwide.lines]].filter(([,current,previous])=>current<previous*(1-baseline.maximumUnapprovedLossRatio));
if(!sourceCounts.operators||!sourceCounts.lines||!sourceCounts.relations||unsafe.length)throw new Error(`Destructive build blocked: ${unsafe.map(([key,current,previous])=>`${key} ${previous} -> ${current}`).join(', ')||'empty source data'}`);
fs.rmSync(path.join(root,'js','rail-data.js'),{force:true});
write('js/nationwide-data.js',`window.TRT_EMBEDDED_NATIONWIDE=${JSON.stringify({index:nationwideIndex,routes:nationwideRoutes})};\n`);
const services=JSON.parse(read('data/services.json')),korean=JSON.parse(read('data/korean-overrides.json'));
write('js/service-data.js',`window.TRT_SERVICE_CATALOG=${JSON.stringify(services.routes)};\nwindow.TRT_KOREAN_OVERRIDES=${JSON.stringify(korean.stations)};\n`);
const lineThemes=JSON.parse(read('data/line-themes.json'));
write('js/line-theme-data.js',`window.TRT_LINE_THEMES=${JSON.stringify(lineThemes.themes)};\n`);
const lineBadges=JSON.parse(read('data/line-badges.json'));
write('js/line-badge-data.js',`window.TRT_LINE_BADGES=${JSON.stringify(lineBadges)};\n`);
const railSystem=JSON.parse(read('data/rail-system.json'));
write('js/rail-system-data.js',`window.TRT_RAIL_SYSTEM=${JSON.stringify(railSystem)};\n`);
const order=['utils.js','rail-data-repository.js','asset-renderer.js','storage.js','typing.js','typing-model.js','statistics-engine.js','line-badge.js','station-sign-templates.js','transport-stop-templates.js','route-integrity.js','route-renderer.js','game.js','statistics.js','network-map.js','data-loader.js','route-editor.js','auth.js','app.js'];
const source=order.map(file=>read(`js/${file}`)
  .replace(/\bimport(?=\s|\{)[^;]+;/g,'')
  .replace(/\bexport\s+/g,'')
  .replace(/new URL\('\.\.\/data\/([^']+)',import\.meta\.url\)/g,"new URL('./data/$1',document.baseURI)"))
  .join('\n\n');
const bundle=`/* AUTO-GENERATED by tools/build-static.js. DO NOT EDIT. */\n(()=>{'use strict';(async()=>{\n${source}\n})().catch(error=>{console.error('Tokyo Rail Typing failed to start:',error);const toast=document.querySelector('#toast');if(toast){toast.textContent='게임을 시작하지 못했습니다. 새로고침해 주세요.';toast.classList.add('show')}})})();\n`;
write('js/app.bundle.js',bundle);
const digest=value=>crypto.createHash('sha256').update(value).digest('hex').slice(0,12),workspaceBrowser=read('js/line-workspace-data.js'),koreaBrowser=read('js/korea-index-data.js');
let html=read('index.html');
html=html.replace(/(\.\/js\/line-workspace-data\.js)(?:\?v=[^"']*)?/g,`$1?v=${digest(workspaceBrowser)}`);
html=html.replace(/(\.\/js\/korea-index-data\.js)(?:\?v=[^"']*)?/g,`$1?v=${digest(koreaBrowser)}`);
html=html.replace(/(\.\/js\/app\.bundle\.js)(?:\?v=[^"']*)?/g,`$1?v=${digest(bundle)}`);
write('index.html',html);
const canonicalAssets=JSON.parse(read('data/generated/asset-registry.json'));
console.log(JSON.stringify({bundle:'js/app.bundle.js',workspaceSource:'data/lines/**/line.json',workspaceBrowserData:'js/line-workspace-data.js',embeddedLines:categories.reduce((sum,category)=>sum+(embedded.lines[category].routes?.length||0),0),embeddedNationwideLines:nationwideIndex.routes?.length||0,embeddedNationwideRouteFiles:Object.keys(nationwideRoutes).length,services:Object.values(services.routes).reduce((sum,list)=>sum+list.length,0),koreanOverrides:Object.keys(korean.stations).length,lineThemes:Object.keys(lineThemes.themes).length,operatorAssets:Object.keys(canonicalAssets.operators||{}).length,lineBadges:Object.keys(lineBadges.routeCodes).length,realSymbolAssets:Object.keys(canonicalAssets.lines||{}).length,railSystem:railSystem.audit},null,2));
