#!/usr/bin/env node
/*
 * Build the static Tokyo rail dataset from EkiData.jp CSV files.
 * Usage:
 *   node tools/generate-data.js --source path/to/csvs
 * Optional modules: kuroshiro, kuroshiro-analyzer-kuromoji, csv-parse.
 */
const fs=require('fs'),path=require('path');
const {parse}=require('csv-parse/sync');
const Kuroshiro=require('kuroshiro').default;
const root=path.resolve(__dirname,'..');
const analyzerPackage=path.join(root,'node_modules','.pnpm','kuroshiro-analyzer-kuromoji@1.1.0','node_modules','kuroshiro-analyzer-kuromoji');
const KuromojiAnalyzer=require(fs.existsSync(analyzerPackage)?analyzerPackage:'kuroshiro-analyzer-kuromoji');
const arg=process.argv.indexOf('--source');
const source=arg>=0?path.resolve(process.argv[arg+1]):path.resolve(root,'../../work/ekidata-src/ekidata-main/csvs');
const nationwide=process.argv.includes('--nationwide');
const oldOdpt=path.resolve(root,'../../work/open-rail-src/open-data-jp-railway-stations-master/stations.json');
const mlitPath=path.resolve(root,'../../work/N02-25/N02-25_GML/UTF-8/N02-25_Station.geojson');
const readCsv=name=>parse(fs.readFileSync(path.join(source,name)),{columns:true,skip_empty_lines:true,relax_quotes:true});
const stations=readCsv('station.csv'),lines=readCsv('line.csv'),companies=readCsv('company.csv');
const companyById=new Map(companies.map(x=>[x.company_cd,x]));
const activeTokyoLineIds=new Set(stations.filter(s=>s.e_status==='0'&&s.pref_cd==='13').map(s=>s.line_cd));
const selectedCompanyIds=new Set(lines.filter(l=>activeTokyoLineIds.has(l.line_cd)).map(l=>l.company_cd));
const connectedLineNames=new Set(['JR根岸線','JR川越線','JR常磐線(取手～いわき)','JR鶴見線','JR相模線','東急新横浜線','小田急江ノ島線','小田急多摩線','相鉄本線','相鉄いずみ野線','相鉄・JR直通線','みなとみらい線','ブルーライン','グリーンライン','金沢シーサイドライン']);
const selectedLines=lines.filter(l=>l.e_status==='0'&&(nationwide||activeTokyoLineIds.has(l.line_cd)||connectedLineNames.has(l.line_name)));
const selectedLineIds=new Set(selectedLines.map(l=>l.line_cd));
const selectedStations=stations.filter(s=>s.e_status==='0'&&selectedLineIds.has(s.line_cd)&&Number(s.lat)&&Number(s.lon));

const officialCodes=new Map();
if(fs.existsSync(oldOdpt))for(const group of JSON.parse(fs.readFileSync(oldOdpt)))for(const s of group.stations||[])if(s.ekidata_id)officialCodes.set(String(s.ekidata_id),s.short_code||'');
const existing=JSON.parse(fs.readFileSync(path.join(root,'data','routes.json'))).routes;
const verifiedNames=new Map();
for(const route of existing)for(const s of route.stations){const v=Array.isArray(s)?{ja:s[1],kana:s[2],romaji:s[3],ko:s[4],koAliases:s[5]||[]} : s;if(v.ja&&!verifiedNames.has(v.ja))verifiedNames.set(v.ja,v)}
const mlitByName=new Map();
if(fs.existsSync(mlitPath)){const geo=JSON.parse(fs.readFileSync(mlitPath));for(const f of geo.features){const name=f.properties?.N02_005,coords=f.geometry?.coordinates;if(!name||!Array.isArray(coords)||!coords.length)continue;const flat=f.geometry.type==='MultiLineString'?coords.flat():coords;const point={longitude:flat.reduce((n,p)=>n+p[0],0)/flat.length,latitude:flat.reduce((n,p)=>n+p[1],0)/flat.length,group:f.properties.N02_005g,company:f.properties.N02_004,line:f.properties.N02_003};if(!mlitByName.has(name))mlitByName.set(name,[]);mlitByName.get(name).push(point)}}

const operatorMeta={
 'JR東日本':['JR East','JR 동일본'], 'JR東海':['JR Central','JR 도카이'], 'JR西日本':['JR West','JR 서일본'], 'JR北海道':['JR Hokkaido','JR 홋카이도'], 'JR九州':['JR Kyushu','JR 규슈'], '東京メトロ':['Tokyo Metro','도쿄 메트로'], '東京都交通局':['Toei Transportation','도에이 교통'], 'Osaka Metro':['Osaka Metro','오사카 메트로'],
 '東急電鉄':['Tokyu','도큐 전철'],'小田急電鉄':['Odakyu','오다큐 전철'],'京王電鉄':['Keio','게이오 전철'],'西武鉄道':['Seibu','세이부 철도'],'東武鉄道':['Tobu','도부 철도'],'京急電鉄':['Keikyu','게이큐 전철'],'京成電鉄':['Keisei','게이세이 전철'],
 '東京モノレール':['Tokyo Monorail','도쿄 모노레일'],'ゆりかもめ':['Yurikamome','유리카모메'],'東京臨海高速鉄道':['Tokyo Waterfront Area Rapid Transit','도쿄 임해고속철도'],'首都圏新都市鉄道':['Metropolitan Intercity Railway','수도권 신도시 철도'],'埼玉高速鉄道':['Saitama Railway','사이타마 고속철도'],'多摩都市モノレール':['Tama Monorail','다마 도시 모노레일'],'北総鉄道':['Hokuso Railway','호쿠소 철도'],'相模鉄道':['Sotetsu','소테츠'],'横浜高速鉄道':['Yokohama Minatomirai Railway','요코하마 고속철도'],'横浜市交通局':['Yokohama Municipal Subway','요코하마 시영 지하철'],'横浜シーサイドライン':['Yokohama Seaside Line','요코하마 시사이드 라인'],'株式会社横浜シーサイドライン':['Yokohama Seaside Line','요코하마 시사이드 라인']
};
const lineMeta={
 'JR山手線':['Yamanote Line','야마노테선','JY','#80c241'], 'JR中央線(快速)':['Chuo Line (Rapid)','츄오선 쾌속','JC','#f15a22'], 'JR中央・総武線':['Chuo-Sobu Line','츄오·소부선','JB','#ffd400'], 'JR京浜東北線':['Keihin-Tohoku Line','게이힌도호쿠선','JK','#00a7e3'], 'JR埼京線':['Saikyo Line','사이쿄선','JA','#00ac9a'], 'JR京葉線':['Keiyo Line','게이요선','JE','#c9242f'], 'JR横須賀線':['Yokosuka Line','요코스카선','JO','#0066b3'], 'JR湘南新宿ライン':['Shonan-Shinjuku Line','쇼난신주쿠라인','JS','#e21f26'],
 '東京メトロ銀座線':['Ginza Line','긴자선','G','#f39700'],'東京メトロ丸ノ内線':['Marunouchi Line','마루노우치선','M','#e60012'],'東京メトロ日比谷線':['Hibiya Line','히비야선','H','#9caeb7'],'東京メトロ東西線':['Tozai Line','도자이선','T','#00a7db'],'東京メトロ千代田線':['Chiyoda Line','지요다선','C','#00bb85'],'東京メトロ有楽町線':['Yurakucho Line','유라쿠초선','Y','#c1a470'],'東京メトロ半蔵門線':['Hanzomon Line','한조몬선','Z','#8f76d6'],'東京メトロ南北線':['Namboku Line','난보쿠선','N','#00ada9'],'東京メトロ副都心線':['Fukutoshin Line','후쿠토신선','F','#9c5e31'],
 '都営浅草線':['Asakusa Line','아사쿠사선','A','#e85298'],'都営三田線':['Mita Line','미타선','I','#0079c2'],'都営新宿線':['Shinjuku Line','신주쿠선','S','#6cbb5a'],'都営大江戸線':['Oedo Line','오에도선','E','#b6007a'],'都電荒川線':['Tokyo Sakura Tram','도쿄 사쿠라 트램','SA','#e85298'],'日暮里・舎人ライナー':['Nippori-Toneri Liner','닛포리·토네리 라이너','NT','#d6c447'],
 '東急東横線':['Toyoko Line','도요코선','TY','#da0442'],'東急田園都市線':['Den-en-toshi Line','덴엔토시선','DT','#20a288'],'小田急線':['Odawara Line','오다와라선','OH','#2288cc'],'京王線':['Keio Line','게이오선','KO','#dd0077'],'西武池袋線':['Ikebukuro Line','이케부쿠로선','SI','#f6b21a'],'東武東上線':['Tojo Line','도조선','TJ','#005bac'],'京急本線':['Keikyu Main Line','게이큐 본선','KK','#00a0e9'],'京成本線':['Keisei Main Line','게이세이 본선','KS','#005aaa'],
 '東急新横浜線':['Tokyu Shin-yokohama Line','도큐 신요코하마선','SH','#6f2e8f'],'相鉄本線':['Sotetsu Main Line','소테츠 본선','SO','#0066b3'],'相鉄いずみ野線':['Sotetsu Izumino Line','소테츠 이즈미노선','SO','#0066b3'],'相鉄・JR直通線':['Sotetsu Shin-yokohama Line','소테츠 신요코하마선','SO','#0066b3'],'みなとみらい線':['Minatomirai Line','미나토미라이선','MM','#0067c0'],'ブルーライン':['Blue Line','블루 라인','B','#006bf1'],'グリーンライン':['Green Line','그린 라인','G','#40a829'],'金沢シーサイドライン':['Kanazawa Seaside Line','가나자와 시사이드 라인','SI','#f59b23'],
 '東京モノレール':['Tokyo Monorail Haneda Airport Line','도쿄 모노레일 하네다 공항선','MO','#0099cc'],'ゆりかもめ':['Yurikamome','유리카모메','U','#0067b0'],'りんかい線':['Rinkai Line','린카이선','R','#00b48d'],'つくばエクスプレス':['Tsukuba Express','츠쿠바 익스프레스','TX','#003399'],'多摩モノレール':['Tama Monorail','다마 모노레일','TT','#ff6600']
 ,'大阪メトロ御堂筋線':['Midosuji Line','미도스지선','M','#e5171f'],'大阪メトロ谷町線':['Tanimachi Line','다니마치선','T','#522886'],'大阪メトロ四つ橋線':['Yotsubashi Line','요쓰바시선','Y','#0078ba'],'大阪メトロ中央線':['Chuo Line','주오선','C','#019a66'],'大阪メトロ千日前線':['Sennichimae Line','센니치마에선','S','#e44d93'],'大阪メトロ堺筋線':['Sakaisuji Line','사카이스지선','K','#814721'],'大阪メトロ長堀鶴見緑地線':['Nagahori Tsurumi-ryokuchi Line','나가호리쓰루미료쿠치선','N','#a9cc51'],'大阪メトロ今里筋線':['Imazatosuji Line','이마자토스지선','I','#ee7b1a'],'大阪メトロ南港ポートタウン線':['New Tram','뉴트램','P','#00a0de']
};
const otherCompanies=new Set(['東京モノレール','ゆりかもめ','東京臨海高速鉄道','首都圏新都市鉄道','埼玉高速鉄道','多摩都市モノレール','北総鉄道']);
const hiraMap={
 'あ':'아','い':'이','う':'우','え':'에','お':'오','か':'카','き':'키','く':'쿠','け':'케','こ':'코','が':'가','ぎ':'기','ぐ':'구','げ':'게','ご':'고','さ':'사','し':'시','す':'스','せ':'세','そ':'소','ざ':'자','じ':'지','ず':'즈','ぜ':'제','ぞ':'조','た':'타','ち':'치','つ':'츠','て':'테','と':'토','だ':'다','ぢ':'지','づ':'즈','で':'데','ど':'도','な':'나','に':'니','ぬ':'누','ね':'네','の':'노','は':'하','ひ':'히','ふ':'후','へ':'헤','ほ':'호','ば':'바','び':'비','ぶ':'부','べ':'베','ぼ':'보','ぱ':'파','ぴ':'피','ぷ':'푸','ぺ':'페','ぽ':'포','ま':'마','み':'미','む':'무','め':'메','も':'모','や':'야','ゆ':'유','よ':'요','ら':'라','り':'리','る':'루','れ':'레','ろ':'로','わ':'와','ゐ':'이','ゑ':'에','を':'오','ゔ':'부',
 'きゃ':'캬','きゅ':'큐','きょ':'쿄','ぎゃ':'갸','ぎゅ':'규','ぎょ':'교','しゃ':'샤','しゅ':'슈','しょ':'쇼','じゃ':'자','じゅ':'주','じょ':'조','ちゃ':'차','ちゅ':'추','ちょ':'초','にゃ':'냐','にゅ':'뉴','にょ':'뇨','ひゃ':'햐','ひゅ':'휴','ひょ':'효','びゃ':'뱌','びゅ':'뷰','びょ':'뵤','ぴゃ':'퍄','ぴゅ':'퓨','ぴょ':'표','みゃ':'먀','みゅ':'뮤','みょ':'묘','りゃ':'랴','りゅ':'류','りょ':'료','ふぁ':'화','ふぃ':'휘','ふぇ':'훼','ふぉ':'훠','てぃ':'티','でぃ':'디','うぃ':'위','うぇ':'웨','うぉ':'워'
};
function addFinal(text,index){if(!text)return text;const cp=text.codePointAt(text.length-1);if(cp>=0xac00&&cp<=0xd7a3&&(cp-0xac00)%28===0)return text.slice(0,-1)+String.fromCodePoint(cp+index);return text}
function kanaToKo(kana){kana=toHiragana(kana).replace(/偕/g,'かい').replace(/曳/g,'ひき').replace(/諫/g,'いさ').replace(/[ヶゖ]/g,'が').replace(/ぢゃ/g,'じゃ').replace(/センタ/g,'せんた').replace(/タミナル/g,'たーみなる');let out='',small=false;for(let i=0;i<kana.length;){let pair=kana.slice(i,i+2);if(kana[i]==='っ'){small=true;i++;continue}if(kana[i]==='ん'){out=addFinal(out,4);i++;continue}if(kana[i]==='ー'){i++;continue}let unit=hiraMap[pair]?pair:kana[i],ko=hiraMap[unit]||unit;if(small){out=addFinal(out,20);small=false}out+=ko;i+=unit.length}return out.replace(/[・･]/g,'·').replace(/[()（）〈〉]/g,'').replace(/[ぁ-んァ-ヶ一-龯]/g,'')}
const roma={'あ':'a','い':'i','う':'u','え':'e','お':'o','か':'ka','き':'ki','く':'ku','け':'ke','こ':'ko','が':'ga','ぎ':'gi','ぐ':'gu','げ':'ge','ご':'go','さ':'sa','し':'shi','す':'su','せ':'se','そ':'so','ざ':'za','じ':'ji','ず':'zu','ぜ':'ze','ぞ':'zo','た':'ta','ち':'chi','つ':'tsu','て':'te','と':'to','だ':'da','で':'de','ど':'do','な':'na','に':'ni','ぬ':'nu','ね':'ne','の':'no','は':'ha','ひ':'hi','ふ':'fu','へ':'he','ほ':'ho','ば':'ba','び':'bi','ぶ':'bu','べ':'be','ぼ':'bo','ぱ':'pa','ぴ':'pi','ぷ':'pu','ぺ':'pe','ぽ':'po','ま':'ma','み':'mi','む':'mu','め':'me','も':'mo','や':'ya','ゆ':'yu','よ':'yo','ら':'ra','り':'ri','る':'ru','れ':'re','ろ':'ro','わ':'wa','を':'o','ん':'n','きゃ':'kya','きゅ':'kyu','きょ':'kyo','ぎゃ':'gya','ぎゅ':'gyu','ぎょ':'gyo','しゃ':'sha','しゅ':'shu','しょ':'sho','じゃ':'ja','じゅ':'ju','じょ':'jo','ちゃ':'cha','ちゅ':'chu','ちょ':'cho','にゃ':'nya','にゅ':'nyu','にょ':'nyo','ひゃ':'hya','ひゅ':'hyu','ひょ':'hyo','びゃ':'bya','びゅ':'byu','びょ':'byo','ぴゃ':'pya','ぴゅ':'pyu','ぴょ':'pyo','みゃ':'mya','みゅ':'myu','みょ':'myo','りゃ':'rya','りゅ':'ryu','りょ':'ryo'};
function toHiragana(value){return String(value||'').replace(/[ァ-ヶ]/g,c=>String.fromCharCode(c.charCodeAt(0)-0x60)).toLowerCase()}
function kanaToRomaji(kana){let out='',geminate=false;for(let i=0;i<kana.length;){if(kana[i]==='っ'){geminate=true;i++;continue}if(kana[i]==='ー'){out+=out.match(/[aeiou](?!.*[aeiou])/g)?.at(-1)||'';i++;continue}const pair=kana.slice(i,i+2),unit=roma[pair]?pair:kana[i],part=roma[unit]||'';out+=(geminate&&part?part[0]:'')+part;geminate=false;i+=unit.length}return out.replace(/^./,c=>c.toUpperCase())}
function colorFor(id){let n=0;for(const c of id)n=(n*31+c.charCodeAt(0))>>>0;return`hsl(${n%360} 62% 46%)`}
function categoryFor(company,line){if(company.startsWith('JR'))return'jr';if(/新幹線/.test(line))return'shinkansen';if(/(札幌市交通局|仙台市交通局|東京メトロ|東京都交通局|横浜市交通局|名古屋市交通局|京都市交通局|大阪市高速電気軌道|Osaka Metro|神戸市交通局|福岡市交通局)/.test(company))return'subway';if(/(軌道|市内線|都電|市電)/.test(line)||/(函館市企業局|熊本市交通局|鹿児島市交通局|とさでん交通|広島電鉄|長崎電気軌道)/.test(company))return'tram';if(otherCompanies.has(company)||/(モノレール|ゆりかもめ|新交通|ガイドウェイ)/.test(`${company}${line}`))return'other';if(/(道南いさりび|青い森|IGRいわて銀河|三陸鉄道|阿武隈急行|会津鉄道|野岩鉄道|わたらせ渓谷|しなの鉄道|えちごトキめき|あいの風とやま|IRいしかわ|ハピライン|伊勢鉄道|智頭急行|北条鉄道|土佐くろしお|肥薩おれんじ|平成筑豊)/.test(company))return'third-sector';return'private'}
function cleanLineName(name){return name.replace(/^JR/,'').replace(/^東京メトロ/,'').replace(/^都営/,'').replace(/^大阪メトロ/,'')}
function cleanKoreanLineName(value){return value.replace(/토우큐우/g,'도큐').replace(/케이오우/g,'게이오').replace(/오다큐우/g,'오다큐').replace(/토우부/g,'도부').replace(/케이세이/g,'게이세이').replace(/추우오우/g,'츄오').replace(/토우카이도우/g,'도카이도').replace(/소우부/g,'소부').replace(/죠우반/g,'조반').replace(/톴테/g,'도리데').replace(/센/g,'선')}

(async()=>{
 const kuroshiro=new Kuroshiro();await kuroshiro.init(new KuromojiAnalyzer());
 const correctedNames=new Map([
  ['取手',{kana:'とりで',romaji:'Toride',ko:'도리데'}],['西取手',{kana:'にしとりで',romaji:'Nishi-toride',ko:'니시토리데'}],
  ['六本木',{kana:'ろっぽんぎ',romaji:'Roppongi',ko:'롯폰기'}],['六本木一丁目',{kana:'ろっぽんぎいっちょうめ',romaji:'Roppongi-itchome',ko:'롯폰기잇초메'}],
  ['札幌',{kana:'さっぽろ',romaji:'Sapporo',ko:'삿포로'}],['大阪',{kana:'おおさか',romaji:'Osaka',ko:'오사카',koAliases:['오오사카']}],
  ['博多',{kana:'はかた',romaji:'Hakata',ko:'하카타'}],['鹿児島中央',{kana:'かごしまちゅうおう',romaji:'Kagoshima-chuo',ko:'가고시마추오'}],
  ['松山',{kana:'まつやま',romaji:'Matsuyama',ko:'마쓰야마'}],['高知',{kana:'こうち',romaji:'Kochi',ko:'고치'}],
  ['長崎',{kana:'ながさき',romaji:'Nagasaki',ko:'나가사키'}],['相野々',{kana:'あいのの',romaji:'Ainono',ko:'아이노노'}],
  ['襟野々',{kana:'えりのの',romaji:'Erinono',ko:'에리노노'}],['新島々',{kana:'しんしましま',romaji:'Shin-shimashima',ko:'신시마시마'}],
  ['佐々',{kana:'さざ',romaji:'Saza',ko:'사자'}],['韓々坂',{kana:'からからざか',romaji:'Karakarazaka',ko:'가라가라자카'}],
  ['人吉温泉',{kana:'ひとよしおんせん',romaji:'Hitoyoshi-onsen',ko:'히토요시온센'}],['お台場海浜公園',{kana:'おだいばかいひんこうえん',romaji:'Odaiba-kaihinkoen',ko:'오다이바카이힌코엔'}]
 ]);
 const cache=new Map();async function names(ja){if(cache.has(ja))return cache.get(ja);const corrected=correctedNames.get(ja),fixed=corrected||verifiedNames.get(ja);let value;if(fixed)value={ja,kana:fixed.kana,romaji:fixed.romaji,ko:fixed.ko,koAliases:fixed.koAliases||[],nameSource:corrected?'manual-reading-correction':'verified-seed'};else{let kana=toHiragana((await kuroshiro.convert(ja,{to:'hiragana',mode:'normal'})).replace(/\s+/g,''));let romaji=await kuroshiro.convert(ja,{to:'romaji',mode:'normal',romajiSystem:'hepburn'});romaji=romaji.replace(/\b\w/g,c=>c.toUpperCase());value={ja,kana,romaji,ko:kanaToKo(kana),koAliases:[],nameSource:'dictionary-transliteration'}}cache.set(ja,value);return value}
 const byLine=new Map();for(const s of selectedStations){if(!byLine.has(s.line_cd))byLine.set(s.line_cd,[]);byLine.get(s.line_cd).push(s)}for(const arr of byLine.values())arr.sort((a,b)=>Number(a.e_sort)-Number(b.e_sort));
 const routes=[];for(const line of selectedLines){const company=companyById.get(line.company_cd)?.company_name||'Unknown';const rawStations=byLine.get(line.line_cd)||[];if(!rawStations.length)continue;const meta=lineMeta[line.line_name],lineReading=await names(cleanLineName(line.line_name)),companyReading=await names(company.replace(/株式会社|旅客鉄道/g,''));const [opEn,opKo]=operatorMeta[company]||[companyReading.romaji,companyReading.ko];const route={id:`line-${line.line_cd}`,sourceLineId:line.line_cd,category:categoryFor(company,line.line_name),operatorId:`op-${line.company_cd}`,operator:{ja:company,en:opEn,ko:opKo},line:{ja:cleanLineName(line.line_name),kana:lineReading.kana,en:meta?.[0]||lineReading.romaji,ko:meta?.[1]||cleanKoreanLineName(lineReading.ko),aliases:[line.line_name,line.line_name_k,line.line_name_h].filter(Boolean)},code:meta?.[2]||'',lineColor:meta?.[3]||line.line_color_c||colorFor(line.line_cd),loop:/山手線|大江戸線/.test(line.line_name),coverage:nationwide?'nationwide-source-line':'full-source-line',verified:'2026-08-22',stations:[]};for(const s of rawStations){const n=await names(s.station_name);route.stations.push({id:s.station_cd,sourceId:s.station_cd,stationMasterId:`station-${s.station_g_cd}`,...n,latitude:Number(s.lat),longitude:Number(s.lon),prefectureCode:Number(s.pref_cd),inTokyo:s.pref_cd==='13'})}if(company==='Osaka Metro'&&meta?.[2]){const starts={M:11,T:11,Y:11,C:10,S:11,K:11,N:11,I:11,P:9},start=starts[meta[2]];if(start)route.stations.forEach((station,index)=>Object.assign(station,{officialCode:`${meta[2]}${start+index}`,stationCodeSource:'Osaka Metro official route map',hasOfficialStationCode:true}))}if(line.line_name==='JR山手線'){const start=route.stations.findIndex(s=>s.ja==='東京');route.stations=Array.from({length:route.stations.length},(_,n)=>route.stations[(start-n+route.stations.length)%route.stations.length])}routes.push(route)}
 // Shinkansen service within and immediately connected to Tokyo, absent from the free station CSV.
 const allSourceByName=new Map(),allSourcesByName=new Map();for(const s of selectedStations){if(!allSourcesByName.has(s.station_name))allSourcesByName.set(s.station_name,[]);allSourcesByName.get(s.station_name).push(s);if(!allSourceByName.has(s.station_name)||s.pref_cd==='13')allSourceByName.set(s.station_name,s)}
 const fallbackShinkansen={
  '新富士':['しんふじ','Shin-fuji','신후지',35.1420,138.6633,22],'岐阜羽島':['ぎふはしま','Gifu-hashima','기후하시마',35.3157,136.6856,21],'新尾道':['しんおのみち','Shin-onomichi','신오노미치',34.4303,133.1907,34],'東広島':['ひがしひろしま','Higashi-hiroshima','히가시히로시마',34.3893,132.7596,34],'新岩国':['しんいわくに','Shin-iwakuni','신이와쿠니',34.1654,132.1487,35],
  '白石蔵王':['しろいしざおう','Shiroishi-zao','시로이시자오',38.0024,140.6327,4],'くりこま高原':['くりこまこうげん','Kurikoma-kogen','구리코마코겐',38.7497,141.0719,4],'水沢江刺':['みずさわえさし','Mizusawa-esashi','미즈사와에사시',39.1456,141.1886,3],'七戸十和田':['しちのへとわだ','Shichinohe-towada','시치노헤토와다',40.7201,141.1538,2],'奥津軽いまべつ':['おくつがるいまべつ','Oku-tsugaru-imabetsu','오쿠쓰가루이마베쓰',41.1452,140.5159,2],
  '本庄早稲田':['ほんじょうわせだ','Honjo-waseda','혼조와세다',36.2180,139.1798,11],'上毛高原':['じょうもうこうげん','Jomo-kogen','조모코겐',36.6935,138.9772,10],'安中榛名':['あんなかはるな','Annaka-haruna','안나카하루나',36.3627,138.8490,10],'黒部宇奈月温泉':['くろべうなづきおんせん','Kurobe-unazukionsen','구로베우나즈키온센',36.8745,137.4800,16],'越前たけふ':['えちぜんたけふ','Echizen-takefu','에치젠타케후',35.9033,136.1715,18],
  '新大牟田':['しんおおむた','Shin-omuta','신오무타',33.0715,130.4890,40],'新玉名':['しんたまな','Shin-tamana','신타마나',32.9405,130.5740,43],'嬉野温泉':['うれしのおんせん','Ureshino-onsen','우레시노온센',33.1048,129.9990,41],'新大村':['しんおおむら','Shin-omura','신오무라',32.9205,129.9590,42]
 };
 async function makeManualRoute(id,ja,en,ko,operator,code,color,namesList,kind='standard'){const ss=[];for(const [stationJa,shortCode]of namesList){const candidates=allSourcesByName.get(stationJa)||stations.filter(s=>s.e_status==='0'&&s.station_name===stationJa&&Number(s.lat)),fallback=fallbackShinkansen[stationJa],operatorStation=candidates.find(s=>companyById.get(lines.find(line=>line.line_cd===s.line_cd)?.company_cd)?.company_name===operator),src=operatorStation||(!fallback&&(allSourceByName.get(stationJa)||candidates[0]));if(!src&&!fallback){console.warn(`Shinkansen station missing: ${stationJa}`);continue}const generated=src?await names(stationJa):{ja:stationJa,kana:fallback[0],romaji:fallback[1],ko:fallback[2],koAliases:[],nameSource:'official-name-manual-reading'};ss.push({id:shortCode,sourceId:src?.station_cd||`manual-${shortCode}`,stationMasterId:src?`station-${src.station_g_cd}`:`station-shinkansen-${shortCode}`,...generated,latitude:Number(src?.lat??fallback[3]),longitude:Number(src?.lon??fallback[4]),prefectureCode:Number(src?.pref_cd??fallback[5]),inTokyo:(src?.pref_cd||fallback[5])==='13'})}const opIds={'JR東海':'op-3','JR東日本':'op-2','JR西日本':'op-jr-west','JR北海道':'op-jr-hokkaido','JR九州':'op-jr-kyushu'};return{id,sourceLineId:id,category:'shinkansen',subCategory:'shinkansen',shinkansenStyle:operator==='JR九州'?'kyushu':operator==='JR東日本'||operator==='JR北海道'?'east':'central-west',shinkansenKind:kind,operatorId:opIds[operator],operator:{ja:operator,en:operatorMeta[operator][0],ko:operatorMeta[operator][1]},line:{ja,en,ko},code,lineColor:color,loop:false,coverage:'full-current-line',sourceUrl:'https://www.japanrailpass-reservation.net/about_jrp/route.html',verifiedDate:'2026-08-22',stations:ss}}
 const seq=(prefix,list)=>list.map((name,i)=>[name,`${prefix}${String(i+1).padStart(2,'0')}`]);
 routes.push(await makeManualRoute('shinkansen-tokaido','東海道新幹線','Tokaido Shinkansen','도카이도 신칸센','JR東海','T','#168f68',seq('T',['東京','品川','新横浜','小田原','熱海','三島','新富士','静岡','掛川','浜松','豊橋','三河安城','名古屋','岐阜羽島','米原','京都','新大阪'])));
 routes.push(await makeManualRoute('shinkansen-sanyo','山陽新幹線','Sanyo Shinkansen','산요 신칸센','JR西日本','S','#1769aa',seq('S',['新大阪','新神戸','西明石','姫路','相生','岡山','新倉敷','福山','新尾道','三原','東広島','広島','新岩国','徳山','新山口','厚狭','新下関','小倉','博多'])));
 routes.push(await makeManualRoute('shinkansen-tohoku','東北新幹線','Tohoku Shinkansen','도호쿠 신칸센','JR東日本','TH','#169b62',seq('TH',['東京','上野','大宮','小山','宇都宮','那須塩原','新白河','郡山','福島','白石蔵王','仙台','古川','くりこま高原','一ノ関','水沢江刺','北上','新花巻','盛岡','いわて沼宮内','二戸','八戸','七戸十和田','新青森'])));
 routes.push(await makeManualRoute('shinkansen-hokkaido','北海道新幹線','Hokkaido Shinkansen','홋카이도 신칸센','JR北海道','H','#7b4a9d',seq('H',['新青森','奥津軽いまべつ','木古内','新函館北斗'])));
 routes.push(await makeManualRoute('shinkansen-joetsu','上越新幹線','Joetsu Shinkansen','조에쓰 신칸센','JR東日本','J','#df245f',seq('J',['東京','上野','大宮','熊谷','本庄早稲田','高崎','上毛高原','越後湯沢','浦佐','長岡','燕三条','新潟'])));
 routes.push(await makeManualRoute('shinkansen-hokuriku','北陸新幹線','Hokuriku Shinkansen','호쿠리쿠 신칸센','JR東日本','W','#0072bc',seq('W',['東京','上野','大宮','熊谷','本庄早稲田','高崎','安中榛名','軽井沢','佐久平','上田','長野','飯山','上越妙高','糸魚川','黒部宇奈月温泉','富山','新高岡','金沢','小松','加賀温泉','芦原温泉','福井','越前たけふ','敦賀'])));
 routes.push(await makeManualRoute('shinkansen-kyushu','九州新幹線','Kyushu Shinkansen','규슈 신칸센','JR九州','K','#e52336',seq('K',['博多','新鳥栖','久留米','筑後船小屋','新大牟田','新玉名','熊本','新八代','新水俣','出水','川内','鹿児島中央'])));
 routes.push(await makeManualRoute('shinkansen-nishi-kyushu','西九州新幹線','Nishi Kyushu Shinkansen','니시큐슈 신칸센','JR九州','N','#ee7623',seq('N',['武雄温泉','嬉野温泉','新大村','諫早','長崎'])));
 routes.push(await makeManualRoute('shinkansen-yamagata','山形新幹線','Yamagata Shinkansen','야마가타 신칸센','JR東日本','Y','#f28e2b',seq('Y',['福島','米沢','高畠','赤湯','かみのやま温泉','山形','天童','さくらんぼ東根','村山','大石田','新庄']),'mini'));
 routes.push(await makeManualRoute('shinkansen-akita','秋田新幹線','Akita Shinkansen','아키타 신칸센','JR東日本','A','#ed2b88',seq('A',['盛岡','雫石','田沢湖','角館','大曲','秋田']),'mini'));
 if(nationwide){
  const write=(rel,data)=>{const file=path.join(root,rel);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(data,null,2)+'\n')};
  const canonical=[...new Map(routes.filter(route=>route.stations.length>=2).map(route=>[`${route.operator.ja}\u0000${route.line.ja}`,route])).values()];
  const stationMap=new Map();
  for(const route of canonical)for(const station of route.stations){const prior=stationMap.get(station.stationMasterId);if(!prior)stationMap.set(station.stationMasterId,{...station,operators:[route.operator.ja],lines:[{routeId:route.id,lineJa:route.line.ja,lineKo:route.line.ko,operatorJa:route.operator.ja}]});else{prior.operators=[...new Set([...prior.operators,route.operator.ja])];if(!prior.lines.some(line=>line.routeId===route.id))prior.lines.push({routeId:route.id,lineJa:route.line.ja,lineKo:route.line.ko,operatorJa:route.operator.ja})}}
  for(const route of canonical){route.stationSequence=route.stations.map(station=>station.stationMasterId);route.dataKind=route.category==='shinkansen'?'shinkansenRoute':'physicalRoute';route.lazySource=`./data/nationwide/routes/${route.id}.json`;write(`data/nationwide/routes/${route.id}.json`,{version:1,route})}
  const operators=[...new Map(canonical.map(route=>[route.operatorId,{id:route.operatorId,...route.operator,category:route.category,lineCount:canonical.filter(item=>item.operatorId===route.operatorId).length}])).values()];
  const indexRoutes=canonical.map(route=>({id:route.id,category:route.category,operatorId:route.operatorId,operator:route.operator,line:route.line,code:route.code,lineColor:route.lineColor,loop:route.loop,stationCount:route.stations.length,stationSequence:route.stationSequence,lazySource:route.lazySource,searchStations:route.stations.flatMap(station=>[station.ja,station.kana,station.romaji,station.ko])}));
  const review=[...stationMap.values()].filter(station=>station.nameSource==='dictionary-transliteration').map(station=>({id:station.stationMasterId,ja:station.ja,kana:station.kana,romaji:station.romaji,ko:station.ko,reason:'automatic-transliteration-requires-human-audit'}));
  const audit={generated:new Date().toISOString(),source:'EkiData station order + MLIT N02 2025 coordinates',operators:operators.length,lines:canonical.length,stations:stationMap.size,byCategory:Object.fromEntries([...new Set(canonical.map(route=>route.category))].sort().map(category=>[category,canonical.filter(route=>route.category===category).length])),missingKoreanLines:canonical.filter(route=>!route.line.ko).length,missingKoreanStations:[...stationMap.values()].filter(station=>!station.ko).length,japaneseCharsInKorean:[...stationMap.values()].filter(station=>/[一-龯々〆ヵヶぁ-ゖァ-ヺ]/.test(station.ko)).length,reviewRequired:review.length,geometryReady:canonical.filter(route=>route.geometry?.length>1).length};
  write('data/nationwide/index.json',{version:1,generated:audit.generated,operators,routes:indexRoutes});write('data/nationwide/stations.json',{version:1,generated:audit.generated,stations:[...stationMap.values()]});write('data/nationwide/REVIEW_REQUIRED.json',review);write('data/nationwide/AUDIT.json',audit);console.log(JSON.stringify(audit,null,2));return
 }
 const routeRefs=new Map();for(const r of routes)for(const s of r.stations){if(!routeRefs.has(s.stationMasterId))routeRefs.set(s.stationMasterId,[]);routeRefs.get(s.stationMasterId).push({routeId:r.id,lineJa:r.line.ja,lineKo:r.line.ko,operatorJa:r.operator.ja,category:r.category,code:s.id})}
 const masters=[];for(const [masterId,refs]of routeRefs){const members=routes.flatMap(r=>r.stations.filter(s=>s.stationMasterId===masterId));const preferred=members.find(s=>s.inTokyo)||members[0];const operators=[...new Set(refs.map(x=>x.operatorJa))];const candidates=mlitByName.get(preferred.ja)||[];let official=candidates.sort((a,b)=>(a.latitude-preferred.latitude)**2+(a.longitude-preferred.longitude)**2-((b.latitude-preferred.latitude)**2+(b.longitude-preferred.longitude)**2))[0];if(official&&Math.hypot(official.latitude-preferred.latitude,official.longitude-preferred.longitude)>.025)official=null;masters.push({id:masterId,ja:preferred.ja,kana:preferred.kana,romaji:preferred.romaji,ko:preferred.ko,koAliases:preferred.koAliases,latitude:official?.latitude??preferred.latitude,longitude:official?.longitude??preferred.longitude,coordinateSource:official?'MLIT-N02-2025':'EkiData.jp',sourceStationGroup:official?.group||preferred.stationMasterId,prefectureCode:preferred.prefectureCode,inTokyo:members.some(s=>s.inTokyo),operators,lines:refs,nameSource:preferred.nameSource,verified:'2026-08-22'})}
 const operators=[...new Set(routes.map(r=>r.operatorId))].map(id=>{const r=routes.find(x=>x.operatorId===id);return{id,...r.operator,category:r.category,lineCount:routes.filter(x=>x.operatorId===id).length}});
 const buckets={jr:[],subway:[],private:[],other:[],shinkansen:[]};for(const r of routes)buckets[r.category].push(r);
 const write=(rel,data)=>{const file=path.join(root,rel);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(data,null,2)+'\n')};
 for(const [category,list]of Object.entries(buckets))write(`data/lines/${category}.json`,{version:2,verified:'2026-08-22',category,routes:list});
 write('data/stations/tokyo-stations.json',{version:2,verified:'2026-08-22',stations:masters});
 write('data/operators/operators.json',{version:2,verified:'2026-08-22',operators});
 const status={operators:operators.length,lines:routes.length,uniqueStations:masters.length,tokyoStations:masters.filter(s=>s.inTokyo).length,byCategory:Object.fromEntries(Object.entries(buckets).map(([k,v])=>[k,{lines:v.length,stationEntries:v.reduce((n,r)=>n+r.stations.length,0)}])),completeness:{coordinates:masters.filter(s=>Number.isFinite(s.latitude)&&Number.isFinite(s.longitude)).length,japanese:masters.filter(s=>s.ja).length,kana:masters.filter(s=>s.kana).length,romaji:masters.filter(s=>s.romaji).length,korean:masters.filter(s=>s.ko).length},coordinateSources:Object.fromEntries([...new Set(masters.map(s=>s.coordinateSource))].map(k=>[k,masters.filter(s=>s.coordinateSource===k).length])),nameSources:Object.fromEntries([...new Set(masters.map(s=>s.nameSource))].map(k=>[k,masters.filter(s=>s.nameSource===k).length]))};
 write('data/metadata/status.json',{version:2,generated:'2026-08-22',status});
 console.log(JSON.stringify(status,null,2));
})().catch(error=>{console.error(error);process.exit(1)});
