#!/usr/bin/env node
const fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'..');
const categories=['jr','subway','private','other','shinkansen'];const files=categories.map(x=>path.join(root,'data','lines',`${x}.json`));
const routes=files.flatMap(file=>JSON.parse(fs.readFileSync(file)).routes);const master=JSON.parse(fs.readFileSync(path.join(root,'data','stations','tokyo-stations.json'))).stations;const services=JSON.parse(fs.readFileSync(path.join(root,'data','services.json'))).routes;const koreanOverrides=JSON.parse(fs.readFileSync(path.join(root,'data','korean-overrides.json'))).stations;const lineThemes=JSON.parse(fs.readFileSync(path.join(root,'data','line-themes.json'))).themes;const operatorAssets=JSON.parse(fs.readFileSync(path.join(root,'data','operator-assets.json'))).operators;const routeSymbols=JSON.parse(fs.readFileSync(path.join(root,'data','route-symbol-assets.json'))).assets;const railSystem=JSON.parse(fs.readFileSync(path.join(root,'data','rail-system.json')));
const errors=[],warnings=[];const duplicates=(arr,key)=>arr.map(key).filter((x,i,a)=>a.indexOf(x)!==i);
for(const id of new Set(duplicates(routes,r=>r.id)))errors.push(`duplicate route id: ${id}`);
for(const id of new Set(duplicates(master,s=>s.id)))errors.push(`duplicate station master id: ${id}`);
const masterIds=new Set(master.map(s=>s.id));
const rad=value=>value*Math.PI/180,km=(a,b)=>{const dLat=rad(b.latitude-a.latitude),dLon=rad(b.longitude-a.longitude),x=Math.sin(dLat/2)**2+Math.cos(rad(a.latitude))*Math.cos(rad(b.latitude))*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))};
for(const r of routes){if(!r.line?.ja||!r.operator?.ja)errors.push(`${r.id}: missing line/operator name`);if(r.stations.length<2)errors.push(`${r.id}: fewer than 2 stations`);if(!Array.isArray(r.geometry)||r.geometry.length<2)errors.push(`${r.id}: missing MLIT rail geometry`);if(r.geometrySource!=='MLIT-N02-2025')errors.push(`${r.id}: unverified geometry source`);const seen=new Set(),stationIds=new Set();for(const [index,s]of r.stations.entries()){if(seen.has(s.sourceId))errors.push(`${r.id}: repeated source station ${s.sourceId}`);if(stationIds.has(s.id))errors.push(`${r.id}: repeated playable station id ${s.id}`);seen.add(s.sourceId);stationIds.add(s.id);for(const field of ['ja','kana','romaji','ko'])if(!s[field])errors.push(`${r.id}/${s.sourceId}: missing ${field}`);if(!Number.isFinite(s.latitude)||s.latitude<20||s.latitude>46)errors.push(`${r.id}/${s.sourceId}: latitude outside Japan`);if(!Number.isFinite(s.longitude)||s.longitude<122||s.longitude>154)errors.push(`${r.id}/${s.sourceId}: longitude outside Japan`);if(!masterIds.has(s.stationMasterId))errors.push(`${r.id}/${s.sourceId}: missing station master`);if(!Number.isInteger(s.geometryIndex)||s.geometryIndex<0||s.geometryIndex>=r.geometry.length)errors.push(`${r.id}/${s.id}: invalid geometry index`);if((s.geometrySnapKm??Infinity)>2)errors.push(`${r.id}/${s.id}: station is ${s.geometrySnapKm}km from geometry`);if(index&&km(r.stations[index-1],s)>500)errors.push(`${r.id}/${s.id}: sudden station jump over 500km`)}}
for(const [routeId,list]of Object.entries(services)){const route=routes.find(item=>item.id===routeId);if(!route){errors.push(`services: unknown route ${routeId}`);continue}const ids=new Set(route.stations.map(station=>station.id));const serviceIds=new Set();for(const service of list){if(serviceIds.has(service.id))errors.push(`${routeId}: duplicate service ${service.id}`);serviceIds.add(service.id);if(!service.nameJa||!service.nameKo||!service.nameEn)errors.push(`${routeId}/${service.id}: missing service name`);if(!Array.isArray(service.stops)||service.stops.length<2)errors.push(`${routeId}/${service.id}: fewer than 2 stops`);for(const stop of service.stops||[])if(!ids.has(stop))errors.push(`${routeId}/${service.id}: unknown stop ${stop}`)}}
for(const [ja,value]of Object.entries(koreanOverrides)){if(!value.ko)errors.push(`korean override ${ja}: missing ko`);if(!routes.some(route=>route.stations.some(station=>station.ja===ja)))warnings.push(`korean override ${ja}: station not found`)}
const colorPattern=/^#[0-9a-f]{6}$/i,routeIds=new Set(routes.map(route=>route.id));
for(const [routeId,theme]of Object.entries(lineThemes)){if(!routeIds.has(routeId))errors.push(`line theme: unknown route ${routeId}`);if(!theme.code)errors.push(`${routeId}: verified theme is missing a line code`);if(!colorPattern.test(theme.color||''))errors.push(`${routeId}: invalid theme color ${theme.color||'(missing)'}`);if(!theme.colorSource)errors.push(`${routeId}: verified theme is missing colorSource`);if(theme.colorVerified!==true)warnings.push(`${routeId}: theme color is not marked verified`);if(theme.stationCodes&&!Object.values(theme.stationCodes).every(code=>typeof code==='string'&&code.length<=8))errors.push(`${routeId}: invalid station code override`)}
for(const [operatorId,asset]of Object.entries(operatorAssets)){const file=path.resolve(root,asset.asset.replace(/^\.\//,''));if(!asset.label||!asset.source||!asset.license)errors.push(`${operatorId}: incomplete operator asset metadata`);if(asset.logoVerified!==true)warnings.push(`${operatorId}: operator asset is not marked verified`);if(!fs.existsSync(file))errors.push(`${operatorId}: missing operator asset ${asset.asset}`);else if(!/<svg[\s>]/i.test(fs.readFileSync(file,'utf8')))errors.push(`${operatorId}: operator asset is not valid SVG`)}
const japanesePattern=/[ぁ-んァ-ヶ一-龯]/u;
const brokenKoPattern=/[～（）]|(?:^|[^가-힣])sen(?:[^가-힣]|$)|(?<!칸)센$/iu;
for(const route of routes){if(japanesePattern.test(route.line?.ko||''))errors.push(`${route.id}: Japanese characters in Korean line name (${route.line.ko})`);if(brokenKoPattern.test(route.line?.ko||''))errors.push(`${route.id}: broken Korean line name (${route.line.ko})`);for(const station of route.stations)if(japanesePattern.test(station.ko||''))errors.push(`${route.id}/${station.id}: Japanese characters in Korean station name (${station.ko})`)}
for(const s of master){if(s.inTokyo&&s.prefectureCode!==13)warnings.push(`${s.id}: inTokyo flag differs from prefecture code`);if(!s.lines?.length)errors.push(`${s.id}: no lines`);if(japanesePattern.test(s.ko||''))errors.push(`${s.id}: Japanese characters in Korean master name (${s.ko})`)}
const lineBadges=JSON.parse(fs.readFileSync(path.join(root,'data','line-badges.json'))),symbolAliases={'op-2':'jr-east','op-18':'tokyo-metro','op-119':'toei','op-16':'tokyu','op-15':'odakyu','op-14':'keio','op-12':'seibu','op-11':'tobu','op-17':'keikyu','op-13':'keisei'},symbolKey=route=>`${symbolAliases[route.operatorId]||route.operatorId}:${lineBadges.routeCodes?.[route.id]||route.code}`;const symbolAudit={totalPlayableLines:routes.length,verified:routes.filter(route=>routeSymbols[symbolKey(route)]).length,missing:routes.filter(route=>!routeSymbols[symbolKey(route)]&&route.officialSymbolExists!==false).map(route=>route.id),noOfficialSymbol:routes.filter(route=>route.officialSymbolExists===false).map(route=>route.id)};
const nationwideIndex=JSON.parse(fs.readFileSync(path.join(root,'data','nationwide','index.json'))),cleanLine=value=>String(value||'').replace(/^JR/,'').replace(/^東京メトロ/,'').replace(/^都営/,'').replace(/^大阪メトロ/,''),knownCatalogKeys=new Set(routes.map(route=>`${route.operator?.ja}\u0000${cleanLine(route.line?.ja)}`)),catalogIds=new Set(routes.map(route=>route.id));let catalogLines=routes.length;for(const route of nationwideIndex.routes||[]){const key=`${route.operator?.ja}\u0000${route.line?.ja}`;if(!knownCatalogKeys.has(key)){catalogLines++;knownCatalogKeys.add(key)}catalogIds.add(route.id)}catalogLines+=['line-11302','line-28001'].filter(id=>!catalogIds.has(id)).length;const nationwideStations=JSON.parse(fs.readFileSync(path.join(root,'data','nationwide','stations.json'))).stations||[];
const result={valid:errors.length===0,operators:(nationwideIndex.operators||[]).length,lines:catalogLines,curatedValidatedLines:routes.length,nationwideSourceLines:(nationwideIndex.routes||[]).length,uniqueStations:nationwideStations.length,curatedStationRegistry:master.length,completeness:{coordinates:master.filter(s=>Number.isFinite(s.latitude)&&Number.isFinite(s.longitude)).length,japanese:master.filter(s=>s.ja).length,kana:master.filter(s=>s.kana).length,romaji:master.filter(s=>s.romaji).length,korean:master.filter(s=>s.ko).length},railSystem:railSystem.audit,geometry:{curatedMatched:routes.filter(route=>Array.isArray(route.geometry)&&route.geometry.length>1).length,curatedTotal:routes.length,nationwideMatched:nationwideIndex.audit?.geometryMatched??null,nationwideTotal:(nationwideIndex.routes||[]).length},operatorAssets:{verified:Object.values(operatorAssets).filter(asset=>asset.logoVerified).length,total:Object.keys(operatorAssets).length},symbolAudit,lineMetadata:{verifiedThemes:Object.keys(lineThemes).length,routesWithoutVerifiedTheme:routes.filter(route=>!lineThemes[route.id]).length,routesWithoutImportedCode:routes.filter(route=>!route.code).length},serviceRoutes:Object.keys(services).length,servicePatterns:Object.values(services).reduce((sum,list)=>sum+list.length,0),koreanOverrides:Object.keys(koreanOverrides).length,errors,warnings};console.log(JSON.stringify(result,null,2));process.exitCode=errors.length?1:0;
